// Copyright (c) 2019 by the SciSharp Team
// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using Cupy.Models;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Cupy.UnitTest
{
    [TestClass]
    public class CuPy_array_creationTest : BaseTestCase
    {
        [TestMethod]
        public void emptyTest()
        {
            var given = cp.empty(new Shape(2, 2), cp.int32);
            Assert.IsTrue(given.repr.StartsWith("array([["));
            Assert.IsTrue(given.repr.EndsWith("]])"));
        }

        [TestMethod]
        public void empty_likeTest()
        {
            var a = new[,] { { 1, 2, 3 }, { 4, 5, 6 } };
            var given = cp.empty_like(a);
            Assert.AreEqual(new Shape(2, 3), given.shape);
            Assert.AreEqual(cp.int32, given.dtype);

            var b = cp.array(new[,] { { 1f, 2f, 3f }, { 4f, 5f, 6f } });
            var c = cp.empty_like(b);
            Assert.AreEqual(new Shape(2, 3), c.shape);
            Assert.AreEqual(cp.float32, c.dtype);
        }

        [TestMethod]
        public void eyeTest()
        {
            // >>> cp.eye(2, dtype=int)
            // array([[1, 0],
            //        [0, 1]])
            // >>> cp.eye(3, k=1)
            // array([[ 0.,  1.,  0.],
            //        [ 0.,  0.,  1.],
            //        [ 0.,  0.,  0.]])
            //           
            var given = cp.eye(2, dtype: cp.int_);
            var expected =
                "array([[1, 0],\n" +
                "       [0, 1]])";
            Assert.AreEqual(expected, given.repr);
            given = cp.eye(3, k: 1);
            expected =
                "array([[0., 1., 0.],\n" +
                "       [0., 0., 1.],\n" +
                "       [0., 0., 0.]])";
            Assert.AreEqual(expected, given.repr);
        }

        [TestMethod]
        public void identityTest()
        {
            // >>> cp.identity(3)
            // array([[ 1.,  0.,  0.],
            //        [ 0.,  1.,  0.],
            //        [ 0.,  0.,  1.]])
            // 
            var given = cp.identity(3);
            var expected =
                "array([[1., 0., 0.],\n" +
                "       [0., 1., 0.],\n" +
                "       [0., 0., 1.]])";
            Assert.AreEqual(expected, given.repr);
        }

        [TestMethod]
        public void onesTest()
        {
            // >>> cp.ones(5)
            // array([ 1.,  1.,  1.,  1.,  1.])
            // 
            var given = cp.ones(5);
            var expected =
                "array([1., 1., 1., 1., 1.])";
            Assert.AreEqual(expected, given.repr);

            // >>> cp.ones((5,), dtype=int)
            // array([1, 1, 1, 1, 1])
            // 

            given = cp.ones(new Shape(5), cp.int_);
            expected =
                "array([1, 1, 1, 1, 1])";
            Assert.AreEqual(expected, given.repr);

            // >>> cp.ones((2, 1))
            // array([[ 1.],
            //        [ 1.]])
            // 

            given = cp.ones(new Shape(2, 1));
            expected =
                "array([[1.],\n" +
                "       [1.]])";
            Assert.AreEqual(expected, given.repr);

            // >>> s = (2,2)
            // >>> cp.ones(s)
            // array([[ 1.,  1.],
            //        [ 1.,  1.]])
            // 

            var s = new Shape(2, 2);
            given = cp.ones(s);
            expected =
                "array([[1., 1.],\n" +
                "       [1., 1.]])";
            Assert.AreEqual(expected, given.repr);
        }

        [TestMethod]
        public void ones_likeTest()
        {
            // >>> x = cp.arange(6)
            // >>> x = x.reshape((2, 3))
            // >>> x
            // array([[0, 1, 2],
            //        [3, 4, 5]])
            // >>> cp.ones_like(x)
            // array([[1, 1, 1],
            //        [1, 1, 1]])
            // 

            var x = cp.arange(6);
            x = x.reshape(2, 3);
            var given = x;
            var expected =
                "array([[0, 1, 2],\n" +
                "       [3, 4, 5]])";
            Assert.AreEqual(expected, given.repr);
            given = cp.ones_like(x);
            expected =
                "array([[1, 1, 1],\n" +
                "       [1, 1, 1]])";
            Assert.AreEqual(expected, given.repr);

            // >>> y = cp.arange(3, dtype=float)
            // >>> y
            // array([ 0.,  1.,  2.])
            // >>> cp.ones_like(y)
            // array([ 1.,  1.,  1.])
            // 

            var y = cp.arange(3, dtype: cp.float_);
            given = y;
            expected =
                "array([0., 1., 2.])";
            Assert.AreEqual(expected, given.repr);
            given = cp.ones_like(y);
            expected =
                "array([1., 1., 1.])";
            Assert.AreEqual(expected, given.repr);
        }

        [TestMethod]
        public void zerosTest()
        {
            // >>> cp.zeros(5)
            // array([ 0.,  0.,  0.,  0.,  0.])
            // 

            var given = cp.zeros(5);
            var expected =
                "array([0., 0., 0., 0., 0.])";
            Assert.AreEqual(expected, given.repr);

            // >>> cp.zeros((5,), dtype=int)
            // array([0, 0, 0, 0, 0])
            // 

#if TODO
             given = cp.zeros((5,), dtype = int);
             expected =
                "array([0, 0, 0, 0, 0])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.zeros((2, 1))
            // array([[ 0.],
            //        [ 0.]])
            // 

#if TODO
             given = cp.zeros((2, 1));
             expected =
                "array([[ 0.],\n" +
                "       [ 0.]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> s = (2,2)
            // >>> cp.zeros(s)
            // array([[ 0.,  0.],
            //        [ 0.,  0.]])
            // 

#if TODO
             given = s = (2,2);
             given = cp.zeros(s);
             expected =
                "array([[ 0.,  0.],\n" +
                "       [ 0.,  0.]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype
            // array([(0, 0), (0, 0)],
            //       dtype=[('x', '<i4'), ('y', '<i4')])
            // 

#if TODO
             given = cp.zeros((2,), dtype = {('x', 'i4'), ('y', 'i4')}) # custom dtype;
             expected =
                "array([(0, 0), (0, 0)],\n" +
                "      dtype=[('x', '<i4'), ('y', '<i4')])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void zeros_likeTest()
        {
            // >>> x = cp.arange(6)
            // >>> x = x.reshape((2, 3))
            // >>> x
            // array([[0, 1, 2],
            //        [3, 4, 5]])
            // >>> cp.zeros_like(x)
            // array([[0, 0, 0],
            //        [0, 0, 0]])
            // 

#if TODO
            var given = x = cp.arange(6);
             given = x = x.reshape((2, 3));
             given = x;
            var expected =
                "array([[0, 1, 2],\n" +
                "       [3, 4, 5]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.zeros_like(x);
             expected =
                "array([[0, 0, 0],\n" +
                "       [0, 0, 0]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> y = cp.arange(3, dtype=float)
            // >>> y
            // array([ 0.,  1.,  2.])
            // >>> cp.zeros_like(y)
            // array([ 0.,  0.,  0.])
            // 

#if TODO
             given = y = cp.arange(3, dtype = float);
             given = y;
             expected =
                "array([ 0.,  1.,  2.])";
            Assert.AreEqual(expected, given.repr);
             given = cp.zeros_like(y);
             expected =
                "array([ 0.,  0.,  0.])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void fullTest()
        {
            // >>> cp.full((2, 2), cp.inf)
            // array([[ inf,  inf],
            //        [ inf,  inf]])
            // >>> cp.full((2, 2), 10)
            // array([[10, 10],
            //        [10, 10]])
            // 

#if TODO
            var given = cp.full((2, 2), cp.inf);
            var expected =
                "array([[ inf,  inf],\n" +
                "       [ inf,  inf]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.full((2, 2), 10);
             expected =
                "array([[10, 10],\n" +
                "       [10, 10]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void full_likeTest()
        {
            // >>> x = cp.arange(6, dtype=int)
            // >>> cp.full_like(x, 1)
            // array([1, 1, 1, 1, 1, 1])
            // >>> cp.full_like(x, 0.1)
            // array([0, 0, 0, 0, 0, 0])
            // >>> cp.full_like(x, 0.1, dtype=cp.double)
            // array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1])
            // >>> cp.full_like(x, cp.nan, dtype=cp.double)
            // array([ nan,  nan,  nan,  nan,  nan,  nan])
            // 

#if TODO
            var given = x = cp.arange(6, dtype = int);
             given = cp.full_like(x, 1);
            var expected =
                "array([1, 1, 1, 1, 1, 1])";
            Assert.AreEqual(expected, given.repr);
             given = cp.full_like(x, 0.1);
             expected =
                "array([0, 0, 0, 0, 0, 0])";
            Assert.AreEqual(expected, given.repr);
             given = cp.full_like(x, 0.1, dtype = cp.double);
             expected =
                "array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1])";
            Assert.AreEqual(expected, given.repr);
             given = cp.full_like(x, cp.nan, dtype = cp.double);
             expected =
                "array([ nan,  nan,  nan,  nan,  nan,  nan])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> y = cp.arange(6, dtype=cp.double)
            // >>> cp.full_like(y, 0.1)
            // array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1])
            // 

#if TODO
             given = y = cp.arange(6, dtype = cp.double);
             given = cp.full_like(y, 0.1);
             expected =
                "array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1])";
            Assert.AreEqual(expected, given.repr);
#endif
        }

        [TestMethod]
        public void arrayLeakTest()
        {
            var arr = new double[10_000_000];
            using (var process = Process.GetCurrentProcess())
            {
                long memStart;

                long getMemAfterGc()
                {
                    GC.Collect(2, GCCollectionMode.Forced, true, true);
                    process.Refresh();
                    return process.PrivateMemorySize64;
                }

                long getOutstandingMem()
                {
                    return getMemAfterGc() - memStart;
                }

                var ones = cp.ones(10_000_000); // python runtime warmup
                ones.Dispose();

                memStart = getMemAfterGc();

                ones = cp.ones(10_000_000);
                Assert.IsTrue(getOutstandingMem() > 70_000_000);
                ones.Dispose();
                Assert.IsTrue(getOutstandingMem() < 1_000_000);

                var array = cp.array(arr);
                Assert.IsTrue(getOutstandingMem() > 70_000_000);
                array.Dispose();
                Assert.IsTrue(getOutstandingMem() < 1_000_000);

                array = cp.array(arr, cp.float32);
                Assert.IsTrue(getOutstandingMem() > 30_000_000);
                array.Dispose();
                Assert.IsTrue(getOutstandingMem() < 1_000_000);
            }
        }

        [TestMethod]
        public void arrayTest()
        {
            // >>> cp.array([1, 2, 3])
            // array([1, 2, 3])
            // 

            NDarray given = cp.array(1, 2, 3);
            var expected =
                "array([1, 2, 3])";
            Assert.AreEqual(expected, given.repr);

            // Upcasting:

            // >>> cp.array([1, 2, 3.0])
            // array([ 1.,  2.,  3.])
            // 


            given = cp.array(1, 2, 3.0);
            expected =
                "array([1., 2., 3.])";
            Assert.AreEqual(expected, given.repr);
            // More than one dimension:

            // >>> cp.array([[1, 2], [3, 4]])
            // array([[1, 2],
            //        [3, 4]])
            // 

            given = cp.array(new[,] { { 1, 2 }, { 3, 4 } });
            expected =
                "array([[1, 2],\n" +
                "       [3, 4]])";
            Assert.AreEqual(expected, given.repr);

            // Minimum dimensions 2:
            // >>> cp.array([1, 2, 3], ndmin=2)
            // array([[1, 2, 3]])
            // 


            given = cp.array(new[] { 1, 2, 3 }, ndmin: 2);
            expected =
                "array([[1, 2, 3]])";
            Assert.AreEqual(expected, given.repr);

            // Type provided:

            // >>> cp.array([1, 2, 3], dtype=complex)
            // array([ 1.+0.j,  2.+0.j,  3.+0.j])
            // 

            given = cp.array(new[] { 1, 2, 3 }, cp.complex_);
            expected =
                "array([1.+0.j, 2.+0.j, 3.+0.j])";
            Assert.AreEqual(expected, given.repr);

            // Data-type consisting of more than one element:

            // >>> x = cp.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
            // >>> x['a']
            // array([1, 3])
            // 

#if TODO
             given = x = cp.array({(1,2),(3,4)},dtype = {('a','<i4'),('b','<i4')});
             given = x['a'];
             expected =
                "array([1, 3])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Creating an array from sub-classes:

            // >>> cp.array(cp.mat('1 2; 3 4'))
            // array([[1, 2],
            //        [3, 4]])
            // 

#if TODO
             given = cp.array(cp.mat('1 2; 3 4'));
             expected =
                "array([[1, 2],\n" +
                "       [3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.array(cp.mat('1 2; 3 4'), subok=True)
            // matrix([[1, 2],
            //         [3, 4]])
            // 

#if TODO
             given = cp.array(cp.mat('1 2; 3 4'), subok = True);
             expected =
                "matrix([[1, 2],\n" +
                "        [3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }

        [TestMethod]
        public void array1Test()
        {
            //>>> a=[]
            //>>> a.append(cp.arange(5))
            //>>> a.append(cp.arange(5))
            //>>> a.append(cp.arange(5))
            //>>> a.append(cp.arange(5))
            //>>> a
            //    [array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]
            //>>> b=cp.array(a)
            //>>> b
            //array([[0, 1, 2, 3, 4],
            //[0, 1, 2, 3, 4]])
            //>>>
            var a = new List<NDarray>();
            a.Add(cp.arange(5));
            a.Add(cp.arange(5));
            var b = cp.array(a);
            Assert.AreEqual("array([[0, 1, 2, 3, 4],\n       [0, 1, 2, 3, 4]])", b.repr);
        }

        [TestMethod]
        public void array2Test()
        {
            //>>> a=cp.array([1, 2, 3])
            //>>> b=cp.array([a, a, a])
            //>>> b
            //array([[1, 2, 3],
            //       [1, 2, 3],
            //       [1, 2, 3]])
            var a = cp.array(1, 2, 3);
            var b = cp.array(new[] { a, a, a });
            Assert.AreEqual("array([[1, 2, 3],\n       [1, 2, 3],\n       [1, 2, 3]])", b.repr);
        }

        [TestMethod]
        public void asarrayTest()
        {
            // Convert a list into an array:

            // >>> a = [1, 2]
            // >>> cp.asarray(a)
            // array([1, 2])
            // 

#if TODO
            var given = a = [1, 2];
             given = cp.asarray(a);
            var expected =
                "array([1, 2])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Existing arrays are not copied:

            // >>> a = cp.array([1, 2])
            // >>> cp.asarray(a) is a
            // True
            // 

#if TODO
             given = a = cp.array({1, 2});
             given = cp.asarray(a) is a;
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
            // If dtype is set, array is copied only if dtype does not match:

            // >>> a = cp.array([1, 2], dtype=cp.float32)
            // >>> cp.asarray(a, dtype=cp.float32) is a
            // True
            // >>> cp.asarray(a, dtype=cp.float64) is a
            // False
            // 

#if TODO
             given = a = cp.array({1, 2}, dtype = cp.float32);
             given = cp.asarray(a, dtype = cp.float32) is a;
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
             given = cp.asarray(a, dtype = cp.float64) is a;
             expected =
                "False";
            Assert.AreEqual(expected, given.repr);
#endif
            // Contrary to asanyarray, ndarray subclasses are not passed through:

            // >>> issubclass(cp.recarray, cp.ndarray)
            // True
            // >>> a = cp.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(cp.recarray)
            // >>> cp.asarray(a) is a
            // False
            // >>> cp.asanyarray(a) is a
            // True
            // 

#if TODO
             given = issubclass(cp.recarray, cp.ndarray);
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
             given = a = cp.array({(1.0, 2), (3.0, 4)}, dtype = 'f4,i4').view(cp.recarray);
             given = cp.asarray(a) is a;
             expected =
                "False";
            Assert.AreEqual(expected, given.repr);
             given = cp.asanyarray(a) is a;
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void asanyarrayTest()
        {
            // Convert a list into an array:

            // >>> a = [1, 2]
            // >>> cp.asanyarray(a)
            // array([1, 2])
            // 

#if TODO
            var given = a = [1, 2];
             given = cp.asanyarray(a);
            var expected =
                "array([1, 2])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Instances of ndarray subclasses are passed through as-is:

            // >>> a = cp.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(cp.recarray)
            // >>> cp.asanyarray(a) is a
            // True
            // 

#if TODO
             given = a = cp.array({(1.0, 2), (3.0, 4)}, dtype = 'f4,i4').view(cp.recarray);
             given = cp.asanyarray(a) is a;
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void ascontiguousarrayTest()
        {
            // >>> x = cp.arange(6).reshape(2,3)
            // >>> cp.ascontiguousarray(x, dtype=cp.float32)
            // array([[ 0.,  1.,  2.],
            //        [ 3.,  4.,  5.]], dtype=float32)
            // >>> x.flags['C_CONTIGUOUS']
            // True
            // 

#if TODO
            var given = x = cp.arange(6).reshape(2,3);
             given = cp.ascontiguousarray(x, dtype = cp.float32);
            var expected =
                "array([[ 0.,  1.,  2.],\n" +
                "       [ 3.,  4.,  5.]], dtype=float32)";
            Assert.AreEqual(expected, given.repr);
             given = x.flags['C_CONTIGUOUS'];
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
            // Note: This function returns an array with at least one-dimension (1-d) 
            // so it will not preserve 0-d arrays.
        }


        [TestMethod]
        public void asmatrixTest()
        {
            // >>> x = cp.array([[1, 2], [3, 4]])
            // 

#if TODO
            var given = x = cp.array({{1, 2}, {3, 4}});
#endif
            // >>> m = cp.asmatrix(x)
            // 

#if TODO
             given = m = cp.asmatrix(x);
#endif
            // >>> x[0,0] = 5
            // 

#if TODO
             given = x[0,0] = 5;
#endif
            // >>> m
            // matrix([[5, 2],
            //         [3, 4]])
            // 

#if TODO
             given = m;
            var expected =
                "matrix([[5, 2],\n" +
                "        [3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void copyTest()
        {
            // Create an array x, with a reference y and a copy z:

            var x = cp.array(1, 2, 3);
            var y = x;
            var z = cp.copy(x);

            // Note that, when we modify x, y changes, but not z:

            x[0] = (NDarray)10;

            Assert.AreEqual(x[0], y[0]);
            Assert.AreNotEqual(x[0], z[0]);
        }


        [TestMethod]
        public void copyTest1()
        {
            // Create an array x, with a reference y and a copy z:

            var x = cp.array(1, 2, 3);
            var y = x;
            var z = x.copy();

            // Note that, when we modify x, y changes, but not z:

            x[0] = (NDarray)10;

            Assert.AreEqual(x[0], y[0]);
            Assert.AreNotEqual(x[0], z[0]);
        }


        [TestMethod]
        public void frombufferTest()
        {
            // >>> s = 'hello world'
            // >>> cp.frombuffer(s, dtype='S1', count=5, offset=6)
            // array(['w', 'o', 'r', 'l', 'd'],
            //       dtype='|S1')
            // 

#if TODO
            var given = s = 'hello world';
             given = cp.frombuffer(s, dtype = 'S1', count = 5, offset = 6);
            var expected =
                "array(['w', 'o', 'r', 'l', 'd'],\n" +
                "      dtype='|S1')";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.frombuffer(b'\x01\x02', dtype=cp.uint8)
            // array([1, 2], dtype=uint8)
            // >>> cp.frombuffer(b'\x01\x02\x03\x04\x05', dtype=cp.uint8, count=3)
            // array([1, 2, 3], dtype=uint8)
            // 

#if TODO
             given = cp.frombuffer(b'\x01\x02', dtype = cp.uint8);
             expected =
                "array([1, 2], dtype=uint8)";
            Assert.AreEqual(expected, given.repr);
             given = cp.frombuffer(b'\x01\x02\x03\x04\x05', dtype = cp.uint8, count = 3);
             expected =
                "array([1, 2, 3], dtype=uint8)";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void fromfileTest()
        {
            // Construct an ndarray:

            // >>> dt = cp.dtype([('time', [('min', int), ('sec', int)]),
            // ...                ('temp', float)])
            // >>> x = cp.zeros((1,), dtype=dt)
            // >>> x['time']['min'] = 10; x['temp'] = 98.25
            // >>> x
            // array([((10, 0), 98.25)],
            //       dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])
            // 

#if TODO
            var given = dt = cp.dtype({('time', {('min', int), ('sec', int)}),;
            var expected =
                "...                ('temp', float)])";
            Assert.AreEqual(expected, given.repr);
             given = x = cp.zeros((1,), dtype = dt);
             given = x['time']['min'] = 10; x['temp'] = 98.25;
             given = x;
             expected =
                "array([((10, 0), 98.25)],\n" +
                "      dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Save the raw data to disk:

            // >>> import os
            // >>> fname = os.tmpnam()
            // >>> x.tofile(fname)
            // 

#if TODO
             given = import os;
             given = fname = os.tmpnam();
             given = x.tofile(fname);
#endif
            // Read the raw data from disk:

            // >>> cp.fromfile(fname, dtype=dt)
            // array([((10, 0), 98.25)],
            //       dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])
            // 

#if TODO
             given = cp.fromfile(fname, dtype = dt);
             expected =
                "array([((10, 0), 98.25)],\n" +
                "      dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])";
            Assert.AreEqual(expected, given.repr);
#endif
            // The recommended way to store and load data:

            // >>> cp.save(fname, x)
            // >>> cp.load(fname + '.npy')
            // array([((10, 0), 98.25)],
            //       dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])
            // 

#if TODO
             given = cp.save(fname, x);
             given = cp.load(fname + '.npy');
             expected =
                "array([((10, 0), 98.25)],\n" +
                "      dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void fromfunctionTest()
        {
            // >>> cp.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
            // array([[ True, False, False],
            //        [False,  True, False],
            //        [False, False,  True]])
            // 

#if TODO
            var given = cp.fromfunction(lambda i, j: i == j, (3, 3), dtype = int);
            var expected =
                "array([[ True, False, False],\n" +
                "       [False,  True, False],\n" +
                "       [False, False,  True]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
            // array([[0, 1, 2],
            //        [1, 2, 3],
            //        [2, 3, 4]])
            // 

#if TODO
             given = cp.fromfunction(lambda i, j: i + j, (3, 3), dtype = int);
             expected =
                "array([[0, 1, 2],\n" +
                "       [1, 2, 3],\n" +
                "       [2, 3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void fromiterTest()
        {
            // >>> iterable = (x*x for x in range(5))
            // >>> cp.fromiter(iterable, float)
            // array([  0.,   1.,   4.,   9.,  16.])
            // 

#if TODO
            var given = iterable = (x*x for x in range(5));
             given = cp.fromiter(iterable, float);
            var expected =
                "array([  0.,   1.,   4.,   9.,  16.])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void fromstringTest()
        {
            // >>> cp.fromstring('1 2', dtype=int, sep=' ')
            // array([1, 2])
            // >>> cp.fromstring('1, 2', dtype=int, sep=',')
            // array([1, 2])
            // 

#if TODO
            var given = cp.fromstring('1 2', dtype = int, sep = ' ');
            var expected =
                "array([1, 2])";
            Assert.AreEqual(expected, given.repr);
             given = cp.fromstring('1, 2', dtype = int, sep = ',');
             expected =
                "array([1, 2])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void loadtxtTest()
        {
            // >>> from io import StringIO   # StringIO behaves like a file object
            // >>> c = StringIO(u"0 1\n2 3")
            // >>> cp.loadtxt(c)
            // array([[ 0.,  1.],
            //        [ 2.,  3.]])
            // 

            var tempFile = Path.GetTempFileName();
            File.WriteAllText(tempFile, "0 1\n2 3");
            var given = cp.loadtxt(tempFile);
            var expected =
                "array([[0., 1.],\n" +
                "       [2., 3.]])";
            Assert.AreEqual(expected, given.repr);


            // >>> c = StringIO(u"1,0,2\n3,0,4")
            // >>> x, y = cp.loadtxt(c, delimiter=',', usecols=(0, 2), unpack=True)
            // >>> x
            // array([ 1.,  3.])
            // >>> y
            // array([ 2.,  4.])
            // 

            File.WriteAllText(tempFile, "1,0,2\n3,0,4");
            var a = cp.loadtxt(tempFile, delimiter: ",", usecols: new[] { 0, 2 }, unpack: true);
            given = a[0];
            expected =
                "array([1., 3.])";
            Assert.AreEqual(expected, given.repr);
            given = a[1];
            expected =
                "array([2., 4.])";
            Assert.AreEqual(expected, given.repr);
        }


        [TestMethod]
        public void loadtxt_custom_dtype()
        {
            // >>> d = StringIO(u"M 21 72\nF 35 58")
            // >>> cp.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),
            // ...                      'formats': ('S1', 'i4', 'f4')})
            // array([('M', 21, 72.0), ('F', 35, 58.0)],
            //       dtype=[('gender', '|S1'), ('age', '<i4'), ('weight', '<f4')])
            // 

#if TODO
             given = d = StringIO(u"M 21 72\nF 35 58");
             given = cp.loadtxt(d, dtype = {'names': ('gender', 'age', 'weight'),;
             expected =
                "...                      'formats': ('S1', 'i4', 'f4')})\n" +
                "array([('M', 21, 72.0), ('F', 35, 58.0)],\n" +
                "      dtype=[('gender', '|S1'), ('age', '<i4'), ('weight', '<f4')])";
            Assert.AreEqual(expected, given.repr);
#endif
        }

        [TestMethod]
        public void chararrayTest()
        {
            // >>> charar = cp.chararray((3, 3))
            // >>> charar[:] = 'a'
            // >>> charar
            // chararray([['a', 'a', 'a'],
            //        ['a', 'a', 'a'],
            //        ['a', 'a', 'a']],
            //       dtype='|S1')
            // 

#if TODO
            var given = charar = cp.chararray((3, 3));
             given = charar[:] = 'a';
             given = charar;
            var expected =
                "chararray([['a', 'a', 'a'],\n" +
                "       ['a', 'a', 'a'],\n" +
                "       ['a', 'a', 'a']],\n" +
                "      dtype='|S1')";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> charar = cp.chararray(charar.shape, itemsize=5)
            // >>> charar[:] = 'abc'
            // >>> charar
            // chararray([['abc', 'abc', 'abc'],
            //        ['abc', 'abc', 'abc'],
            //        ['abc', 'abc', 'abc']],
            //       dtype='|S5')
            // 

#if TODO
             given = charar = cp.chararray(charar.shape, itemsize = 5);
             given = charar[:] = 'abc';
             given = charar;
             expected =
                "chararray([['abc', 'abc', 'abc'],\n" +
                "       ['abc', 'abc', 'abc'],\n" +
                "       ['abc', 'abc', 'abc']],\n" +
                "      dtype='|S5')";
            Assert.AreEqual(expected, given.repr);
#endif
            // Methods
        }


        [TestMethod]
        public void arangeTest()
        {
            // >>> cp.arange(3)
            // array([0, 1, 2])
            // >>> cp.arange(3.0)
            // array([ 0.,  1.,  2.])
            // >>> cp.arange(3,7)
            // array([3, 4, 5, 6])
            // >>> cp.arange(3,7,2)
            // array([3, 5])
            // 

#if TODO
            var given = cp.arange(3);
            var expected =
                "array([0, 1, 2])";
            Assert.AreEqual(expected, given.repr);
             given = cp.arange(3.0);
             expected =
                "array([ 0.,  1.,  2.])";
            Assert.AreEqual(expected, given.repr);
             given = cp.arange(3,7);
             expected =
                "array([3, 4, 5, 6])";
            Assert.AreEqual(expected, given.repr);
             given = cp.arange(3,7,2);
             expected =
                "array([3, 5])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void linspaceTest()
        {
            // >>> cp.linspace(2.0, 3.0, num=5)
            // array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])
            // >>> cp.linspace(2.0, 3.0, num=5, endpoint=False)
            // array([ 2. ,  2.2,  2.4,  2.6,  2.8])
            // >>> cp.linspace(2.0, 3.0, num=5, retstep=True)
            // (array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)
            // 

            var given = cp.linspace(2.0, 3.0, 5);
            var expected =
                "array([2.  , 2.25, 2.5 , 2.75, 3.  ])";
            Assert.AreEqual(expected, given.repr);
            given = cp.linspace(2.0, 3.0, 5, false);
            expected =
                "array([2. , 2.2, 2.4, 2.6, 2.8])";
            Assert.AreEqual(expected, given.repr);
            given = cp.linspace(2, 3, out var step, 5, true);
            expected =
                "array([2.  , 2.25, 2.5 , 2.75, 3.  ])";
            Assert.AreEqual(expected, given.repr);
            Assert.AreEqual(step, 0.25);
        }


        [TestMethod]
        public void logspaceTest()
        {
            // >>> cp.logspace(2.0, 3.0, num=4)
            // array([  100.        ,   215.443469  ,   464.15888336,  1000.        ])
            // >>> cp.logspace(2.0, 3.0, num=4, endpoint=False)
            // array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519])
            // >>> cp.logspace(2.0, 3.0, num=4, base=2.0)
            // array([ 4.        ,  5.0396842 ,  6.34960421,  8.        ])
            // 

#if TODO
            var given = cp.logspace(2.0, 3.0, num = 4);
            var expected =
                "array([  100.        ,   215.443469  ,   464.15888336,  1000.        ])";
            Assert.AreEqual(expected, given.repr);
             given = cp.logspace(2.0, 3.0, num = 4, endpoint = False);
             expected =
                "array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519])";
            Assert.AreEqual(expected, given.repr);
             given = cp.logspace(2.0, 3.0, num = 4, base = 2.0);
             expected =
                "array([ 4.        ,  5.0396842 ,  6.34960421,  8.        ])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Graphical illustration:

            // >>> import matplotlib.pyplot as plt
            // >>> N = 10
            // >>> x1 = cp.logspace(0.1, 1, N, endpoint=True)
            // >>> x2 = cp.logspace(0.1, 1, N, endpoint=False)
            // >>> y = cp.zeros(N)
            // >>> plt.plot(x1, y, 'o')
            // [<matplotlib.lines.Line2D object at 0x...>]
            // >>> plt.plot(x2, y + 0.5, 'o')
            // [<matplotlib.lines.Line2D object at 0x...>]
            // >>> plt.ylim([-0.5, 1])
            // (-0.5, 1)
            // >>> plt.show()
            // 

#if TODO
             given = import matplotlib.pyplot as plt;
             given = N = 10;
             given = x1 = cp.logspace(0.1, 1, N, endpoint = True);
             given = x2 = cp.logspace(0.1, 1, N, endpoint = False);
             given = y = cp.zeros(N);
             given = plt.plot(x1, y, 'o');
             expected =
                "[<matplotlib.lines.Line2D object at 0x...>]";
            Assert.AreEqual(expected, given.repr);
             given = plt.plot(x2, y + 0.5, 'o');
             expected =
                "[<matplotlib.lines.Line2D object at 0x...>]";
            Assert.AreEqual(expected, given.repr);
             given = plt.ylim([-0.5, 1]);
             expected =
                "(-0.5, 1)";
            Assert.AreEqual(expected, given.repr);
             given = plt.show();
#endif
        }


        [TestMethod]
        public void geomspaceTest()
        {
            // >>> cp.geomspace(1, 1000, num=4)
            // array([    1.,    10.,   100.,  1000.])
            // >>> cp.geomspace(1, 1000, num=3, endpoint=False)
            // array([   1.,   10.,  100.])
            // >>> cp.geomspace(1, 1000, num=4, endpoint=False)
            // array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ])
            // >>> cp.geomspace(1, 256, num=9)
            // array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.])
            // 

#if TODO
            var given = cp.geomspace(1, 1000, num = 4);
            var expected =
                "array([    1.,    10.,   100.,  1000.])";
            Assert.AreEqual(expected, given.repr);
             given = cp.geomspace(1, 1000, num = 3, endpoint = False);
             expected =
                "array([   1.,   10.,  100.])";
            Assert.AreEqual(expected, given.repr);
             given = cp.geomspace(1, 1000, num = 4, endpoint = False);
             expected =
                "array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ])";
            Assert.AreEqual(expected, given.repr);
             given = cp.geomspace(1, 256, num = 9);
             expected =
                "array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Note that the above may not produce exact integers:

            // >>> cp.geomspace(1, 256, num=9, dtype=int)
            // array([  1,   2,   4,   7,  16,  32,  63, 127, 256])
            // >>> cp.around(cp.geomspace(1, 256, num=9)).astype(int)
            // array([  1,   2,   4,   8,  16,  32,  64, 128, 256])
            // 

#if TODO
             given = cp.geomspace(1, 256, num = 9, dtype = int);
             expected =
                "array([  1,   2,   4,   7,  16,  32,  63, 127, 256])";
            Assert.AreEqual(expected, given.repr);
             given = cp.around(cp.geomspace(1, 256, num = 9)).astype(int);
             expected =
                "array([  1,   2,   4,   8,  16,  32,  64, 128, 256])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Negative, decreasing, and complex inputs are allowed:

            // >>> cp.geomspace(1000, 1, num=4)
            // array([ 1000.,   100.,    10.,     1.])
            // >>> cp.geomspace(-1000, -1, num=4)
            // array([-1000.,  -100.,   -10.,    -1.])
            // >>> cp.geomspace(1j, 1000j, num=4)  # Straight line
            // array([ 0.   +1.j,  0.  +10.j,  0. +100.j,  0.+1000.j])
            // >>> cp.geomspace(-1+0j, 1+0j, num=5)  # Circle
            // array([-1.00000000+0.j        , -0.70710678+0.70710678j,
            //         0.00000000+1.j        ,  0.70710678+0.70710678j,
            //         1.00000000+0.j        ])
            // 

#if TODO
             given = cp.geomspace(1000, 1, num = 4);
             expected =
                "array([ 1000.,   100.,    10.,     1.])";
            Assert.AreEqual(expected, given.repr);
             given = cp.geomspace(-1000, -1, num = 4);
             expected =
                "array([-1000.,  -100.,   -10.,    -1.])";
            Assert.AreEqual(expected, given.repr);
             given = cp.geomspace(1j, 1000j, num = 4)  # Straight line;
             expected =
                "array([ 0.   +1.j,  0.  +10.j,  0. +100.j,  0.+1000.j])";
            Assert.AreEqual(expected, given.repr);
             given = cp.geomspace(-1+0j, 1+0j, num = 5)  # Circle;
             expected =
                "array([-1.00000000+0.j        , -0.70710678+0.70710678j,\n" +
                "        0.00000000+1.j        ,  0.70710678+0.70710678j,\n" +
                "        1.00000000+0.j        ])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Graphical illustration of endpoint parameter:

            // >>> import matplotlib.pyplot as plt
            // >>> N = 10
            // >>> y = cp.zeros(N)
            // >>> plt.semilogx(cp.geomspace(1, 1000, N, endpoint=True), y + 1, 'o')
            // >>> plt.semilogx(cp.geomspace(1, 1000, N, endpoint=False), y + 2, 'o')
            // >>> plt.axis([0.5, 2000, 0, 3])
            // >>> plt.grid(True, color='0.7', linestyle='-', which='both', axis='both')
            // >>> plt.show()
            // 

#if TODO
             given = import matplotlib.pyplot as plt;
             given = N = 10;
             given = y = cp.zeros(N);
             given = plt.semilogx(cp.geomspace(1, 1000, N, endpoint = True), y + 1, 'o');
             given = plt.semilogx(cp.geomspace(1, 1000, N, endpoint = False), y + 2, 'o');
             given = plt.axis([0.5, 2000, 0, 3]);
             given = plt.grid(True, color = '0.7', linestyle = '-', which = 'both', axis = 'both');
             given = plt.show();
#endif
        }


        [TestMethod]
        public void meshgridTest()
        {
            // >>> nx, ny = (3, 2)
            // >>> x = cp.linspace(0, 1, nx)
            // >>> y = cp.linspace(0, 1, ny)
            // >>> xv, yv = cp.meshgrid(x, y)
            // >>> xv
            // array([[ 0. ,  0.5,  1. ],
            //        [ 0. ,  0.5,  1. ]])
            // >>> yv
            // array([[ 0.,  0.,  0.],
            //        [ 1.,  1.,  1.]])
            // >>> xv, yv = cp.meshgrid(x, y, sparse=True)  # make sparse output arrays
            // >>> xv
            // array([[ 0. ,  0.5,  1. ]])
            // >>> yv
            // array([[ 0.],
            //        [ 1.]])
            // 
            var (nx, ny) = (3, 2);
            var x = cp.linspace(0, 1, nx);
            var y = cp.linspace(0, 1, ny);
            var xv_yv = cp.meshgrid(x, y);
            var given = xv_yv[0];
            var expected =
                "array([[0. , 0.5, 1. ],\n" +
                "       [0. , 0.5, 1. ]])";
            Assert.AreEqual(expected, given.repr);
            given = xv_yv[1];
            expected =
                "array([[0., 0., 0.],\n" +
                "       [1., 1., 1.]])";
            Assert.AreEqual(expected, given.repr);
            xv_yv = cp.meshgrid(new[] { x, y }, sparse: true); // make sparse output arrays;
            given = xv_yv[0];
            expected =
                "array([[0. , 0.5, 1. ]])";
            Assert.AreEqual(expected, given.repr);
            given = xv_yv[1];
            expected =
                "array([[0.],\n" +
                "       [1.]])";
            Assert.AreEqual(expected, given.repr);
        }


        [TestMethod]
        public void mgridTest()
        {
            // >>> cp.mgrid[0:5,0:5]
            // array([[[0, 0, 0, 0, 0],
            //         [1, 1, 1, 1, 1],
            //         [2, 2, 2, 2, 2],
            //         [3, 3, 3, 3, 3],
            //         [4, 4, 4, 4, 4]],
            //        [[0, 1, 2, 3, 4],
            //         [0, 1, 2, 3, 4],
            //         [0, 1, 2, 3, 4],
            //         [0, 1, 2, 3, 4],
            //         [0, 1, 2, 3, 4]]])
            // >>> cp.mgrid[-1:1:5j]
            // array([-1. , -0.5,  0. ,  0.5,  1. ])
            // 

#if TODO
            var given = cp.mgrid["0:5,0:5"];
            var expected =
                "array([[[0, 0, 0, 0, 0],\n" +
                "        [1, 1, 1, 1, 1],\n" +
                "        [2, 2, 2, 2, 2],\n" +
                "        [3, 3, 3, 3, 3],\n" +
                "        [4, 4, 4, 4, 4]],\n" +
                "       [[0, 1, 2, 3, 4],\n" +
                "        [0, 1, 2, 3, 4],\n" +
                "        [0, 1, 2, 3, 4],\n" +
                "        [0, 1, 2, 3, 4],\n" +
                "        [0, 1, 2, 3, 4]]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.mgrid{-1:1:5j};
             expected =
                "array([-1. , -0.5,  0. ,  0.5,  1. ])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void ogridTest()
        {
            // >>> from Cupy import ogrid
            // >>> ogrid[-1:1:5j]
            // array([-1. , -0.5,  0. ,  0.5,  1. ])
            // >>> ogrid[0:5,0:5]
            // [array([[0],
            //         [1],
            //         [2],
            //         [3],
            //         [4]]), array([[0, 1, 2, 3, 4]])]
            // 

#if TODO
            var given = from Cupy import ogrid;
             given = ogrid[-1:1:5j];
            var expected =
                "array([-1. , -0.5,  0. ,  0.5,  1. ])";
            Assert.AreEqual(expected, given.repr);
             given = ogrid[0:5,0:5];
             expected =
                "[array([[0],\n" +
                "        [1],\n" +
                "        [2],\n" +
                "        [3],\n" +
                "        [4]]), array([[0, 1, 2, 3, 4]])]";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void diagTest()
        {
            // >>> x = cp.arange(9).reshape((3,3))
            // >>> x
            // array([[0, 1, 2],
            //        [3, 4, 5],
            //        [6, 7, 8]])
            // 

#if TODO
            var given = x = cp.arange(9).reshape((3,3));
             given = x;
            var expected =
                "array([[0, 1, 2],\n" +
                "       [3, 4, 5],\n" +
                "       [6, 7, 8]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.diag(x)
            // array([0, 4, 8])
            // >>> cp.diag(x, k=1)
            // array([1, 5])
            // >>> cp.diag(x, k=-1)
            // array([3, 7])
            // 

#if TODO
             given = cp.diag(x);
             expected =
                "array([0, 4, 8])";
            Assert.AreEqual(expected, given.repr);
             given = cp.diag(x, k = 1);
             expected =
                "array([1, 5])";
            Assert.AreEqual(expected, given.repr);
             given = cp.diag(x, k = -1);
             expected =
                "array([3, 7])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.diag(cp.diag(x))
            // array([[0, 0, 0],
            //        [0, 4, 0],
            //        [0, 0, 8]])
            // 

#if TODO
             given = cp.diag(cp.diag(x));
             expected =
                "array([[0, 0, 0],\n" +
                "       [0, 4, 0],\n" +
                "       [0, 0, 8]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void diagflatTest()
        {
            // >>> cp.diagflat([[1,2], [3,4]])
            // array([[1, 0, 0, 0],
            //        [0, 2, 0, 0],
            //        [0, 0, 3, 0],
            //        [0, 0, 0, 4]])
            // 

#if TODO
            var given = cp.diagflat({{1,2}, {3,4}});
            var expected =
                "array([[1, 0, 0, 0],\n" +
                "       [0, 2, 0, 0],\n" +
                "       [0, 0, 3, 0],\n" +
                "       [0, 0, 0, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.diagflat([1,2], 1)
            // array([[0, 1, 0],
            //        [0, 0, 2],
            //        [0, 0, 0]])
            // 

#if TODO
             given = cp.diagflat({1,2}, 1);
             expected =
                "array([[0, 1, 0],\n" +
                "       [0, 0, 2],\n" +
                "       [0, 0, 0]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void triTest()
        {
            // >>> cp.tri(3, 5, 2, dtype=int)
            // array([[1, 1, 1, 0, 0],
            //        [1, 1, 1, 1, 0],
            //        [1, 1, 1, 1, 1]])
            // 

#if TODO
            var given = cp.tri(3, 5, 2, dtype = int);
            var expected =
                "array([[1, 1, 1, 0, 0],\n" +
                "       [1, 1, 1, 1, 0],\n" +
                "       [1, 1, 1, 1, 1]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.tri(3, 5, -1)
            // array([[ 0.,  0.,  0.,  0.,  0.],
            //        [ 1.,  0.,  0.,  0.,  0.],
            //        [ 1.,  1.,  0.,  0.,  0.]])
            // 

#if TODO
             given = cp.tri(3, 5, -1);
             expected =
                "array([[ 0.,  0.,  0.,  0.,  0.],\n" +
                "       [ 1.,  0.,  0.,  0.,  0.],\n" +
                "       [ 1.,  1.,  0.,  0.,  0.]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void trilTest()
        {
            // >>> cp.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
            // array([[ 0,  0,  0],
            //        [ 4,  0,  0],
            //        [ 7,  8,  0],
            //        [10, 11, 12]])
            // 

#if TODO
            var given = cp.tril({{1,2,3},{4,5,6},{7,8,9},{10,11,12}}, -1);
            var expected =
                "array([[ 0,  0,  0],\n" +
                "       [ 4,  0,  0],\n" +
                "       [ 7,  8,  0],\n" +
                "       [10, 11, 12]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void vanderTest()
        {
            // >>> x = cp.array([1, 2, 3, 5])
            // >>> N = 3
            // >>> cp.vander(x, N)
            // array([[ 1,  1,  1],
            //        [ 4,  2,  1],
            //        [ 9,  3,  1],
            //        [25,  5,  1]])
            // 

#if TODO
            var given = x = cp.array({1, 2, 3, 5});
             given = N = 3;
             given = cp.vander(x, N);
            var expected =
                "array([[ 1,  1,  1],\n" +
                "       [ 4,  2,  1],\n" +
                "       [ 9,  3,  1],\n" +
                "       [25,  5,  1]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.column_stack([x**(N-1-i) for i in range(N)])
            // array([[ 1,  1,  1],
            //        [ 4,  2,  1],
            //        [ 9,  3,  1],
            //        [25,  5,  1]])
            // 

#if TODO
             given = cp.column_stack({x**(N-1-i) for i in range(N)});
             expected =
                "array([[ 1,  1,  1],\n" +
                "       [ 4,  2,  1],\n" +
                "       [ 9,  3,  1],\n" +
                "       [25,  5,  1]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.array([1, 2, 3, 5])
            // >>> cp.vander(x)
            // array([[  1,   1,   1,   1],
            //        [  8,   4,   2,   1],
            //        [ 27,   9,   3,   1],
            //        [125,  25,   5,   1]])
            // >>> cp.vander(x, increasing=True)
            // array([[  1,   1,   1,   1],
            //        [  1,   2,   4,   8],
            //        [  1,   3,   9,  27],
            //        [  1,   5,  25, 125]])
            // 

#if TODO
             given = x = cp.array({1, 2, 3, 5});
             given = cp.vander(x);
             expected =
                "array([[  1,   1,   1,   1],\n" +
                "       [  8,   4,   2,   1],\n" +
                "       [ 27,   9,   3,   1],\n" +
                "       [125,  25,   5,   1]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.vander(x, increasing = True);
             expected =
                "array([[  1,   1,   1,   1],\n" +
                "       [  1,   2,   4,   8],\n" +
                "       [  1,   3,   9,  27],\n" +
                "       [  1,   5,  25, 125]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // The determinant of a square Vandermonde matrix is the product
            // of the differences between the values of the input vector:

            // >>> cp.linalg.det(cp.vander(x))
            // 48.000000000000043
            // >>> (5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)
            // 48
            // 

#if TODO
             given = cp.linalg.det(cp.vander(x));
             expected =
                "48.000000000000043";
            Assert.AreEqual(expected, given.repr);
             given = (5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1);
             expected =
                "48";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void matTest()
        {
            // >>> x = cp.array([[1, 2], [3, 4]])
            // 

#if TODO
            var given = x = cp.array({{1, 2}, {3, 4}});
#endif
            // >>> m = cp.asmatrix(x)
            // 

#if TODO
             given = m = cp.asmatrix(x);
#endif
            // >>> x[0,0] = 5
            // 

#if TODO
             given = x[0,0] = 5;
#endif
            // >>> m
            // matrix([[5, 2],
            //         [3, 4]])
            // 

#if TODO
             given = m;
            var expected =
                "matrix([[5, 2],\n" +
                "        [3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [TestMethod]
        public void bmatTest()
        {
            // >>> A = cp.mat('1 1; 1 1')
            // >>> B = cp.mat('2 2; 2 2')
            // >>> C = cp.mat('3 4; 5 6')
            // >>> D = cp.mat('7 8; 9 0')
            // 

#if TODO
            var given = A = cp.mat('1 1; 1 1');
             given = B = cp.mat('2 2; 2 2');
             given = C = cp.mat('3 4; 5 6');
             given = D = cp.mat('7 8; 9 0');
#endif
            // All the following expressions construct the same block matrix:

            // >>> cp.bmat([[A, B], [C, D]])
            // matrix([[1, 1, 2, 2],
            //         [1, 1, 2, 2],
            //         [3, 4, 7, 8],
            //         [5, 6, 9, 0]])
            // >>> cp.bmat(cp.r_[cp.c_[A, B], cp.c_[C, D]])
            // matrix([[1, 1, 2, 2],
            //         [1, 1, 2, 2],
            //         [3, 4, 7, 8],
            //         [5, 6, 9, 0]])
            // >>> cp.bmat('A,B; C,D')
            // matrix([[1, 1, 2, 2],
            //         [1, 1, 2, 2],
            //         [3, 4, 7, 8],
            //         [5, 6, 9, 0]])
            // 

#if TODO
             given = cp.bmat({{A, B}, {C, D}});
            var expected =
                "matrix([[1, 1, 2, 2],\n" +
                "        [1, 1, 2, 2],\n" +
                "        [3, 4, 7, 8],\n" +
                "        [5, 6, 9, 0]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.bmat(cp.r_{cp.c_{A, B}, cp.c_{C, D}});
             expected =
                "matrix([[1, 1, 2, 2],\n" +
                "        [1, 1, 2, 2],\n" +
                "        [3, 4, 7, 8],\n" +
                "        [5, 6, 9, 0]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.bmat('A,B; C,D');
             expected =
                "matrix([[1, 1, 2, 2],\n" +
                "        [1, 1, 2, 2],\n" +
                "        [3, 4, 7, 8],\n" +
                "        [5, 6, 9, 0]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }
    }
}