// Copyright (c) 2020 by Meinrad Recheis (Member of SciSharp)
// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using NUnit.Framework;
#if PYTHON_INCLUDED
using Python.Included;
#endif

namespace Cupy.UnitTest
{
    [TestFixture]
    public class Cupy_otherTest : BaseTestCase
    {
        [Test]
        public void rootsTest()
        {
            // >>> coeff = [3.2, 2, 1]
            // >>> cp.roots(coeff)
            // array([-0.3125+0.46351241j, -0.3125-0.46351241j])
            // 

#if TODO
            var given = coeff = [3.2, 2, 1];
             given = cp.roots(coeff);
            var expected =
                "array([-0.3125+0.46351241j, -0.3125-0.46351241j])";
            Assert.That(expected, given.repr);
#endif
        }
    }
}