// Copyright (c) 2019 by the SciSharp Team
// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using Cupy.Models;
using NUnit.Framework;

namespace Cupy.UnitTest
{
    [TestFixture]
    public class CuPy_array_manipulationTest : BaseTestCase
    {
        [Test]
        public void reshapeTest()
        {
            // >>> a = cp.array([[1,2,3], [4,5,6]])
            // >>> cp.reshape(a, 6)
            // array([1, 2, 3, 4, 5, 6])
            // >>> cp.reshape(a, 6, order='F')
            // array([1, 4, 2, 5, 3, 6])
            // 

            var a = cp.array(new[,] { { 1, 2, 3 }, { 4, 5, 6 } });
            var given = cp.reshape(a, 6);
            var expected =
                "array([1, 2, 3, 4, 5, 6])";
            Assert.AreEqual(expected, given.repr);
            given = a.reshape(new Shape(6), "F");
            expected =
                "array([1, 4, 2, 5, 3, 6])";
            Assert.AreEqual(expected, given.repr);
            // >>> cp.reshape(a, (3,-1))       # the unspecified value is inferred to be 2
            // array([[1, 2],
            //        [3, 4],
            //        [5, 6]])
            // 

            given = cp.reshape(a, 3, -1); // the unspecified value is inferred to be 2;
            expected =
                "array([[1, 2],\n" +
                "       [3, 4],\n" +
                "       [5, 6]])";
            Assert.AreEqual(expected, given.repr);
        }


        [Test]
        public void ravelTest()
        {
            // It is equivalent to reshape(-1, order=order).

            // >>> x = cp.array([[1, 2, 3], [4, 5, 6]])
            // >>> print(cp.ravel(x))
            // [1 2 3 4 5 6]
            // 

#if TODO
            var given = x = cp.array({{1, 2, 3}, {4, 5, 6}});
             given = print(cp.ravel(x));
            var expected =
                "[1 2 3 4 5 6]";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> print(x.reshape(-1))
            // [1 2 3 4 5 6]
            // 

#if TODO
             given = print(x.reshape(-1));
             expected =
                "[1 2 3 4 5 6]";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> print(cp.ravel(x, order='F'))
            // [1 4 2 5 3 6]
            // 

#if TODO
             given = print(cp.ravel(x, order = 'F'));
             expected =
                "[1 4 2 5 3 6]";
            Assert.AreEqual(expected, given.repr);
#endif
            // When order is ‘A’, it will preserve the array’s ‘C’ or ‘F’ ordering:

            // >>> print(cp.ravel(x.T))
            // [1 4 2 5 3 6]
            // >>> print(cp.ravel(x.T, order='A'))
            // [1 2 3 4 5 6]
            // 

#if TODO
             given = print(cp.ravel(x.T));
             expected =
                "[1 4 2 5 3 6]";
            Assert.AreEqual(expected, given.repr);
             given = print(cp.ravel(x.T, order = 'A'));
             expected =
                "[1 2 3 4 5 6]";
            Assert.AreEqual(expected, given.repr);
#endif
            // When order is ‘K’, it will preserve orderings that are neither ‘C’
            // nor ‘F’, but won’t reverse axes:

            // >>> a = cp.arange(3)[::-1]; a
            // array([2, 1, 0])
            // >>> a.ravel(order='C')
            // array([2, 1, 0])
            // >>> a.ravel(order='K')
            // array([2, 1, 0])
            // 

#if TODO
             given = a = cp.arange(3){::-1}; a;
             expected =
                "array([2, 1, 0])";
            Assert.AreEqual(expected, given.repr);
             given = a.ravel(order = 'C');
             expected =
                "array([2, 1, 0])";
            Assert.AreEqual(expected, given.repr);
             given = a.ravel(order = 'K');
             expected =
                "array([2, 1, 0])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> a = cp.arange(12).reshape(2,3,2).swapaxes(1,2); a
            // array([[[ 0,  2,  4],
            //         [ 1,  3,  5]],
            //        [[ 6,  8, 10],
            //         [ 7,  9, 11]]])
            // >>> a.ravel(order='C')
            // array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])
            // >>> a.ravel(order='K')
            // array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
            // 

#if TODO
             given = a = cp.arange(12).reshape(2,3,2).swapaxes(1,2); a;
             expected =
                "array([[[ 0,  2,  4],\n" +
                "        [ 1,  3,  5]],\n" +
                "       [[ 6,  8, 10],\n" +
                "        [ 7,  9, 11]]])";
            Assert.AreEqual(expected, given.repr);
             given = a.ravel(order = 'C');
             expected =
                "array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])";
            Assert.AreEqual(expected, given.repr);
             given = a.ravel(order = 'K');
             expected =
                "array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void flattenTest()
        {
            // >>> a = cp.array([[1,2], [3,4]])
            // >>> a.flatten()
            // array([1, 2, 3, 4])
            // >>> a.flatten('F')
            // array([1, 3, 2, 4])
            // 

#if TODO
            var given = a = cp.array({{1,2}, {3,4}});
             given = a.flatten();
            var expected =
                "array([1, 2, 3, 4])";
            Assert.AreEqual(expected, given.repr);
             given = a.flatten('F');
             expected =
                "array([1, 3, 2, 4])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void moveaxisTest()
        {
            // >>> x = cp.zeros((3, 4, 5))
            // >>> cp.moveaxis(x, 0, -1).shape
            // (4, 5, 3)
            // >>> cp.moveaxis(x, -1, 0).shape
            // (5, 3, 4)
            // 

#if TODO
            var given = x = cp.zeros((3, 4, 5));
             given = cp.moveaxis(x, 0, -1).shape;
            var expected =
                "(4, 5, 3)";
            Assert.AreEqual(expected, given.repr);
             given = cp.moveaxis(x, -1, 0).shape;
             expected =
                "(5, 3, 4)";
            Assert.AreEqual(expected, given.repr);
#endif
            // These all achieve the same result:

            // >>> cp.transpose(x).shape
            // (5, 4, 3)
            // >>> cp.swapaxes(x, 0, -1).shape
            // (5, 4, 3)
            // >>> cp.moveaxis(x, [0, 1], [-1, -2]).shape
            // (5, 4, 3)
            // >>> cp.moveaxis(x, [0, 1, 2], [-1, -2, -3]).shape
            // (5, 4, 3)
            // 

#if TODO
             given = cp.transpose(x).shape;
             expected =
                "(5, 4, 3)";
            Assert.AreEqual(expected, given.repr);
             given = cp.swapaxes(x, 0, -1).shape;
             expected =
                "(5, 4, 3)";
            Assert.AreEqual(expected, given.repr);
             given = cp.moveaxis(x, {0, 1}, {-1, -2}).shape;
             expected =
                "(5, 4, 3)";
            Assert.AreEqual(expected, given.repr);
             given = cp.moveaxis(x, {0, 1, 2}, {-1, -2, -3}).shape;
             expected =
                "(5, 4, 3)";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void rollaxisTest()
        {
            // >>> a = cp.ones((3,4,5,6))
            // >>> cp.rollaxis(a, 3, 1).shape
            // (3, 6, 4, 5)
            // >>> cp.rollaxis(a, 2).shape
            // (5, 3, 4, 6)
            // >>> cp.rollaxis(a, 1, 4).shape
            // (3, 5, 6, 4)
            // 

#if TODO
            var given = a = cp.ones((3,4,5,6));
             given = cp.rollaxis(a, 3, 1).shape;
            var expected =
                "(3, 6, 4, 5)";
            Assert.AreEqual(expected, given.repr);
             given = cp.rollaxis(a, 2).shape;
             expected =
                "(5, 3, 4, 6)";
            Assert.AreEqual(expected, given.repr);
             given = cp.rollaxis(a, 1, 4).shape;
             expected =
                "(3, 5, 6, 4)";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void swapaxesTest()
        {
            // >>> x = cp.array([[1,2,3]])
            // >>> cp.swapaxes(x,0,1)
            // array([[1],
            //        [2],
            //        [3]])
            // 

#if TODO
            var given = x = cp.array({{1,2,3}});
             given = cp.swapaxes(x,0,1);
            var expected =
                "array([[1],\n" +
                "       [2],\n" +
                "       [3]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.array([[[0,1],[2,3]],[[4,5],[6,7]]])
            // >>> x
            // array([[[0, 1],
            //         [2, 3]],
            //        [[4, 5],
            //         [6, 7]]])
            // 

#if TODO
             given = x = cp.array({{{0,1},{2,3}},{{4,5},{6,7}}});
             given = x;
             expected =
                "array([[[0, 1],\n" +
                "        [2, 3]],\n" +
                "       [[4, 5],\n" +
                "        [6, 7]]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.swapaxes(x,0,2)
            // array([[[0, 4],
            //         [2, 6]],
            //        [[1, 5],
            //         [3, 7]]])
            // 

#if TODO
             given = cp.swapaxes(x,0,2);
             expected =
                "array([[[0, 4],\n" +
                "        [2, 6]],\n" +
                "       [[1, 5],\n" +
                "        [3, 7]]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void transposeTest()
        {
            // >>> x = cp.arange(4).reshape((2,2))
            // >>> x
            // array([[0, 1],
            //        [2, 3]])
            // 

#if TODO
            var given = x = cp.arange(4).reshape((2,2));
             given = x;
            var expected =
                "array([[0, 1],\n" +
                "       [2, 3]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.transpose(x)
            // array([[0, 2],
            //        [1, 3]])
            // 

#if TODO
             given = cp.transpose(x);
             expected =
                "array([[0, 2],\n" +
                "       [1, 3]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.ones((1, 2, 3))
            // >>> cp.transpose(x, (1, 0, 2)).shape
            // (2, 1, 3)
            // 

#if TODO
             given = x = cp.ones((1, 2, 3));
             given = cp.transpose(x, (1, 0, 2)).shape;
             expected =
                "(2, 1, 3)";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void atleast_1dTest()
        {
            // >>> cp.atleast_1d(1.0)
            // array([ 1.])
            // 

#if TODO
            var given = cp.atleast_1d(1.0);
            var expected =
                "array([ 1.])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.arange(9.0).reshape(3,3)
            // >>> cp.atleast_1d(x)
            // array([[ 0.,  1.,  2.],
            //        [ 3.,  4.,  5.],
            //        [ 6.,  7.,  8.]])
            // >>> cp.atleast_1d(x) is x
            // True
            // 

#if TODO
             given = x = cp.arange(9.0).reshape(3,3);
             given = cp.atleast_1d(x);
             expected =
                "array([[ 0.,  1.,  2.],\n" +
                "       [ 3.,  4.,  5.],\n" +
                "       [ 6.,  7.,  8.]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.atleast_1d(x) is x;
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.atleast_1d(1, [3, 4])
            // [array([1]), array([3, 4])]
            // 

#if TODO
             given = cp.atleast_1d(1, {3, 4});
             expected =
                "[array([1]), array([3, 4])]";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void atleast_2dTest()
        {
            // >>> cp.atleast_2d(3.0)
            // array([[ 3.]])
            // 

#if TODO
            var given = cp.atleast_2d(3.0);
            var expected =
                "array([[ 3.]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.arange(3.0)
            // >>> cp.atleast_2d(x)
            // array([[ 0.,  1.,  2.]])
            // >>> cp.atleast_2d(x).base is x
            // True
            // 

#if TODO
             given = x = cp.arange(3.0);
             given = cp.atleast_2d(x);
             expected =
                "array([[ 0.,  1.,  2.]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.atleast_2d(x).base is x;
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.atleast_2d(1, [1, 2], [[1, 2]])
            // [array([[1]]), array([[1, 2]]), array([[1, 2]])]
            // 

#if TODO
             given = cp.atleast_2d(1, {1, 2}, {{1, 2}});
             expected =
                "[array([[1]]), array([[1, 2]]), array([[1, 2]])]";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void atleast_3dTest()
        {
            // >>> cp.atleast_3d(3.0)
            // array([[[ 3.]]])
            // 

#if TODO
            var given = cp.atleast_3d(3.0);
            var expected =
                "array([[[ 3.]]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.arange(3.0)
            // >>> cp.atleast_3d(x).shape
            // (1, 3, 1)
            // 

#if TODO
             given = x = cp.arange(3.0);
             given = cp.atleast_3d(x).shape;
             expected =
                "(1, 3, 1)";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.arange(12.0).reshape(4,3)
            // >>> cp.atleast_3d(x).shape
            // (4, 3, 1)
            // >>> cp.atleast_3d(x).base is x.base  # x is a reshape, so not base itself
            // True
            // 

#if TODO
             given = x = cp.arange(12.0).reshape(4,3);
             given = cp.atleast_3d(x).shape;
             expected =
                "(4, 3, 1)";
            Assert.AreEqual(expected, given.repr);
             given = cp.atleast_3d(x).base is x.base  # x is a reshape, so not base itself;
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> for arr in cp.atleast_3d([1, 2], [[1, 2]], [[[1, 2]]]):
            // ...     print(arr, arr.shape)
            // ...
            // [[[1]
            //   [2]]] (1, 2, 1)
            // [[[1]
            //   [2]]] (1, 2, 1)
            // [[[1 2]]] (1, 1, 2)
            // 

#if TODO
             given = for arr in cp.atleast_3d({1, 2}, {{1, 2}}, {{{1, 2}}}):;
             expected =
                "...     print(arr, arr.shape)\n" +
                "...\n" +
                "[[[1]\n" +
                "  [2]]] (1, 2, 1)\n" +
                "[[[1]\n" +
                "  [2]]] (1, 2, 1)\n" +
                "[[[1 2]]] (1, 1, 2)";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void broadcastTest()
        {
            // Manually adding two vectors, using broadcasting:

            // >>> x = cp.array([[1], [2], [3]])
            // >>> y = cp.array([4, 5, 6])
            // >>> b = cp.broadcast(x, y)
            // 

#if TODO
            var given = x = cp.array({{1}, {2}, {3}});
             given = y = cp.array({4, 5, 6});
             given = b = cp.broadcast(x, y);
#endif
            // >>> out = cp.empty(b.shape)
            // >>> out.flat = [u+v for (u,v) in b]
            // >>> out
            // array([[ 5.,  6.,  7.],
            //        [ 6.,  7.,  8.],
            //        [ 7.,  8.,  9.]])
            // 

#if TODO
             given = out = cp.empty(b.shape);
             given = out.flat = [u+v for (u,v) in b];
             given = out;
            var expected =
                "array([[ 5.,  6.,  7.],\n" +
                "       [ 6.,  7.,  8.],\n" +
                "       [ 7.,  8.,  9.]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Compare against built-in broadcasting:

            // >>> x + y
            // array([[5, 6, 7],
            //        [6, 7, 8],
            //        [7, 8, 9]])
            // 

#if TODO
             given = x + y;
             expected =
                "array([[5, 6, 7],\n" +
                "       [6, 7, 8],\n" +
                "       [7, 8, 9]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.array([1, 2, 3])
            // >>> y = cp.array([[4], [5], [6]])
            // >>> b = cp.broadcast(x, y)
            // >>> b.nd
            // 2
            // 

#if TODO
             given = x = cp.array({1, 2, 3});
             given = y = cp.array({{4}, {5}, {6}});
             given = b = cp.broadcast(x, y);
             given = b.nd;
             expected =
                "2";
            Assert.AreEqual(expected, given.repr);
#endif
            // Methods
        }


        [Test]
        public void broadcast_toTest()
        {
            // >>> x = cp.array([1, 2, 3])
            // >>> cp.broadcast_to(x, (3, 3))
            // array([[1, 2, 3],
            //        [1, 2, 3],
            //        [1, 2, 3]])
            // 

#if TODO
            var given = x = cp.array({1, 2, 3});
             given = cp.broadcast_to(x, (3, 3));
            var expected =
                "array([[1, 2, 3],\n" +
                "       [1, 2, 3],\n" +
                "       [1, 2, 3]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void broadcast_arraysTest()
        {
            // >>> x = cp.array([[1,2,3]])
            // >>> y = cp.array([[4],[5]])
            // >>> cp.broadcast_arrays(x, y)
            // [array([[1, 2, 3],
            //        [1, 2, 3]]), array([[4, 4, 4],
            //        [5, 5, 5]])]
            // 

#if TODO
            var given = x = cp.array({{1,2,3}});
             given = y = cp.array({{4},{5}});
             given = cp.broadcast_arrays(x, y);
            var expected =
                "[array([[1, 2, 3],\n" +
                "       [1, 2, 3]]), array([[4, 4, 4],\n" +
                "       [5, 5, 5]])]";
            Assert.AreEqual(expected, given.repr);
#endif
            // Here is a useful idiom for getting contiguous copies instead of
            // non-contiguous views.

            // >>> [cp.array(a) for a in cp.broadcast_arrays(x, y)]
            // [array([[1, 2, 3],
            //        [1, 2, 3]]), array([[4, 4, 4],
            //        [5, 5, 5]])]
            // 

#if TODO
             given = {cp.array(a) for a in cp.broadcast_arrays(x, y)};
             expected =
                "[array([[1, 2, 3],\n" +
                "       [1, 2, 3]]), array([[4, 4, 4],\n" +
                "       [5, 5, 5]])]";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void expand_dimsTest()
        {
            // >>> x = cp.array([1,2])
            // >>> x.shape
            // (2,)
            // 

#if TODO
            var given = x = cp.array({1,2});
             given = x.shape;
            var expected =
                "(2,)";
            Assert.AreEqual(expected, given.repr);
#endif
            // The following is equivalent to x[cp.newaxis,:] or x[cp.newaxis]:

            // >>> y = cp.expand_dims(x, axis=0)
            // >>> y
            // array([[1, 2]])
            // >>> y.shape
            // (1, 2)
            // 

#if TODO
             given = y = cp.expand_dims(x, axis = 0);
             given = y;
             expected =
                "array([[1, 2]])";
            Assert.AreEqual(expected, given.repr);
             given = y.shape;
             expected =
                "(1, 2)";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> y = cp.expand_dims(x, axis=1)  # Equivalent to x[:,cp.newaxis]
            // >>> y
            // array([[1],
            //        [2]])
            // >>> y.shape
            // (2, 1)
            // 

#if TODO
             given = y = cp.expand_dims(x, axis = 1)  # Equivalent to x{:,cp.newaxis};
             given = y;
             expected =
                "array([[1],\n" +
                "       [2]])";
            Assert.AreEqual(expected, given.repr);
             given = y.shape;
             expected =
                "(2, 1)";
            Assert.AreEqual(expected, given.repr);
#endif
            // Note that some examples may use None instead of cp.newaxis.  These
            // are the same objects:

            // >>> cp.newaxis is None
            // True
            // 

#if TODO
             given = cp.newaxis is None;
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void squeezeTest()
        {
            // >>> x = cp.array([[[0], [1], [2]]])
            // >>> x.shape
            // (1, 3, 1)
            // >>> cp.squeeze(x).shape
            // (3,)
            // >>> cp.squeeze(x, axis=0).shape
            // (3, 1)
            // >>> cp.squeeze(x, axis=1).shape
            // Traceback (most recent call last):
            // ...
            // ValueError: cannot select an axis to squeeze out which has size not equal to one
            // >>> cp.squeeze(x, axis=2).shape
            // (1, 3)
            // 

#if TODO
            var given = x = cp.array({{{0}, {1}, {2}}});
             given = x.shape;
            var expected =
                "(1, 3, 1)";
            Assert.AreEqual(expected, given.repr);
             given = cp.squeeze(x).shape;
             expected =
                "(3,)";
            Assert.AreEqual(expected, given.repr);
             given = cp.squeeze(x, axis = 0).shape;
             expected =
                "(3, 1)";
            Assert.AreEqual(expected, given.repr);
             given = cp.squeeze(x, axis = 1).shape;
             expected =
                "Traceback (most recent call last):\n" +
                "...\n" +
                "ValueError: cannot select an axis to squeeze out which has size not equal to one";
            Assert.AreEqual(expected, given.repr);
             given = cp.squeeze(x, axis = 2).shape;
             expected =
                "(1, 3)";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void asfarrayTest()
        {
            // >>> cp.asfarray([2, 3])
            // array([ 2.,  3.])
            // >>> cp.asfarray([2, 3], dtype='float')
            // array([ 2.,  3.])
            // >>> cp.asfarray([2, 3], dtype='int8')
            // array([ 2.,  3.])
            // 

#if TODO
            var given = cp.asfarray({2, 3});
            var expected =
                "array([ 2.,  3.])";
            Assert.AreEqual(expected, given.repr);
             given = cp.asfarray({2, 3}, dtype = 'float');
             expected =
                "array([ 2.,  3.])";
            Assert.AreEqual(expected, given.repr);
             given = cp.asfarray({2, 3}, dtype = 'int8');
             expected =
                "array([ 2.,  3.])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void asfortranarrayTest()
        {
            // >>> x = cp.arange(6).reshape(2,3)
            // >>> y = cp.asfortranarray(x)
            // >>> x.flags['F_CONTIGUOUS']
            // False
            // >>> y.flags['F_CONTIGUOUS']
            // True
            // 

#if TODO
            var given = x = cp.arange(6).reshape(2,3);
             given = y = cp.asfortranarray(x);
             given = x.flags['F_CONTIGUOUS'];
            var expected =
                "False";
            Assert.AreEqual(expected, given.repr);
             given = y.flags['F_CONTIGUOUS'];
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
            // Note: This function returns an array with at least one-dimension (1-d) 
            // so it will not preserve 0-d arrays.
        }


        [Test]
        public void asarray_chkfiniteTest()
        {
            // Convert a list into an array.  If all elements are finite
            // asarray_chkfinite is identical to asarray.

            // >>> a = [1, 2]
            // >>> cp.asarray_chkfinite(a, dtype=float)
            // array([1., 2.])
            // 

#if TODO
            var given = a = [1, 2];
             given = cp.asarray_chkfinite(a, dtype = float);
            var expected =
                "array([1., 2.])";
            Assert.AreEqual(expected, given.repr);
#endif
            // Raises ValueError if array_like contains Nans or Infs.

            // >>> a = [1, 2, cp.inf]
            // >>> try:
            // ...     cp.asarray_chkfinite(a)
            // ... except ValueError:
            // ...     print('ValueError')
            // ...
            // ValueError
            // 

#if TODO
             given = a = {1, 2, cp.inf};
             given = try:;
             expected =
                "...     cp.asarray_chkfinite(a)\n" +
                "... except ValueError:\n" +
                "...     print('ValueError')\n" +
                "...\n" +
                "ValueError";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void asscalarTest()
        {
            // >>> cp.asscalar(cp.array([24]))
            // 24
            // 

#if TODO
            var given = cp.asscalar(cp.array({24}));
            var expected =
                "24";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void requireTest()
        {
            // >>> x = cp.arange(6).reshape(2,3)
            // >>> x.flags
            //   C_CONTIGUOUS : True
            //   F_CONTIGUOUS : False
            //   OWNDATA : False
            //   WRITEABLE : True
            //   ALIGNED : True
            //   WRITEBACKIFCOPY : False
            //   UPDATEIFCOPY : False
            // 

#if TODO
            var given = x = cp.arange(6).reshape(2,3);
             given = x.flags;
            var expected =
                "  C_CONTIGUOUS : True\n" +
                "  F_CONTIGUOUS : False\n" +
                "  OWNDATA : False\n" +
                "  WRITEABLE : True\n" +
                "  ALIGNED : True\n" +
                "  WRITEBACKIFCOPY : False\n" +
                "  UPDATEIFCOPY : False";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> y = cp.require(x, dtype=cp.float32, requirements=['A', 'O', 'W', 'F'])
            // >>> y.flags
            //   C_CONTIGUOUS : False
            //   F_CONTIGUOUS : True
            //   OWNDATA : True
            //   WRITEABLE : True
            //   ALIGNED : True
            //   WRITEBACKIFCOPY : False
            //   UPDATEIFCOPY : False
            // 

#if TODO
             given = y = cp.require(x, dtype = cp.float32, requirements = {'A', 'O', 'W', 'F'});
             given = y.flags;
             expected =
                "  C_CONTIGUOUS : False\n" +
                "  F_CONTIGUOUS : True\n" +
                "  OWNDATA : True\n" +
                "  WRITEABLE : True\n" +
                "  ALIGNED : True\n" +
                "  WRITEBACKIFCOPY : False\n" +
                "  UPDATEIFCOPY : False";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void concatenateTest()
        {
            // >>> a = cp.array([[1, 2], [3, 4]])
            // >>> b = cp.array([[5, 6]])
            // >>> cp.concatenate((a, b), axis=0)
            // array([[1, 2],
            //        [3, 4],
            //        [5, 6]])
            // >>> cp.concatenate((a, b.T), axis=1)
            // array([[1, 2, 5],
            //        [3, 4, 6]])
            // >>> cp.concatenate((a, b), axis=None)
            // array([1, 2, 3, 4, 5, 6])
            // 


            var a = cp.array(new[,] { { 1, 2 }, { 3, 4 } });
            var b = cp.array(new[,] { { 5, 6 } });
            var given = cp.concatenate(new[] { a, b });
            var expected =
                "array([[1, 2],\n" +
                "       [3, 4],\n" +
                "       [5, 6]])";
            Assert.AreEqual(expected, given.repr);
            given = cp.concatenate((a, b.T), 1);
            expected =
                "array([[1, 2, 5],\n" +
                "       [3, 4, 6]])";
            Assert.AreEqual(expected, given.repr);
            given = cp.concatenate((a, b), null);
            expected =
                "array([1, 2, 3, 4, 5, 6])";
            Assert.AreEqual(expected, given.repr);
        }

        [Ignore("cp.ma not wrapped yet")]
        public void ConcatenateMaskedArrayTest()
        {
            // This function will not preserve masking of MaskedArray inputs.

            // >>> a = cp.ma.arange(3)
            // >>> a[1] = cp.ma.masked
            // >>> b = cp.arange(2, 5)
            // >>> a
            // masked_array(data=[0, --, 2],
            //              mask=[False,  True, False],
            //        fill_value=999999)
            // >>> b
            // array([2, 3, 4])
            // >>> cp.concatenate([a, b])
            // masked_array(data=[0, 1, 2, 2, 3, 4],
            //              mask=False,
            //        fill_value=999999)
            // >>> cp.ma.concatenate([a, b])
            // masked_array(data=[0, --, 2, 2, 3, 4],
            //              mask=[False,  True, False, False, False, False],
            //        fill_value=999999)
            // 

#if TODO
             given = a = cp.ma.arange(3);
             given = a{1} = cp.ma.masked;
             given = b = cp.arange(2, 5);
             given = a;
             expected =
                "masked_array(data=[0, --, 2],\n" +
                "             mask=[False,  True, False],\n" +
                "       fill_value=999999)";
            Assert.AreEqual(expected, given.repr);
             given = b;
             expected =
                "array([2, 3, 4])";
            Assert.AreEqual(expected, given.repr);
             given = cp.concatenate({a, b});
             expected =
                "masked_array(data=[0, 1, 2, 2, 3, 4],\n" +
                "             mask=False,\n" +
                "       fill_value=999999)";
            Assert.AreEqual(expected, given.repr);
             given = cp.ma.concatenate({a, b});
             expected =
                "masked_array(data=[0, --, 2, 2, 3, 4],\n" +
                "             mask=[False,  True, False, False, False, False],\n" +
                "       fill_value=999999)";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void stackTest()
        {
            // >>> arrays = [cp.random.randn(3, 4) for _ in range(10)]
            // >>> cp.stack(arrays, axis=0).shape
            // (10, 3, 4)
            // 

#if TODO
            var given = arrays = {cp.random.randn(3, 4) for _ in range(10)};
             given = cp.stack(arrays, axis = 0).shape;
            var expected =
                "(10, 3, 4)";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.stack(arrays, axis=1).shape
            // (3, 10, 4)
            // 

#if TODO
             given = cp.stack(arrays, axis = 1).shape;
             expected =
                "(3, 10, 4)";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.stack(arrays, axis=2).shape
            // (3, 4, 10)
            // 

#if TODO
             given = cp.stack(arrays, axis = 2).shape;
             expected =
                "(3, 4, 10)";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> a = cp.array([1, 2, 3])
            // >>> b = cp.array([2, 3, 4])
            // >>> cp.stack((a, b))
            // array([[1, 2, 3],
            //        [2, 3, 4]])
            // 

#if TODO
             given = a = cp.array({1, 2, 3});
             given = b = cp.array({2, 3, 4});
             given = cp.stack((a, b));
             expected =
                "array([[1, 2, 3],\n" +
                "       [2, 3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.stack((a, b), axis=-1)
            // array([[1, 2],
            //        [2, 3],
            //        [3, 4]])
            // 

#if TODO
             given = cp.stack((a, b), axis = -1);
             expected =
                "array([[1, 2],\n" +
                "       [2, 3],\n" +
                "       [3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void column_stackTest()
        {
            // >>> a = cp.array((1,2,3))
            // >>> b = cp.array((2,3,4))
            // >>> cp.column_stack((a,b))
            // array([[1, 2],
            //        [2, 3],
            //        [3, 4]])
            // 

            var a = cp.array(1, 2, 3);
            var b = cp.array(2, 3, 4);
            var given = cp.column_stack(a, b);
            var expected =
                "array([[1, 2],\n" +
                "       [2, 3],\n" +
                "       [3, 4]])";
            Assert.AreEqual(expected, given.repr);
        }


        [Test]
        public void dstackTest()
        {
            // >>> a = cp.array((1,2,3))
            // >>> b = cp.array((2,3,4))
            // >>> cp.dstack((a,b))
            // array([[[1, 2],
            //         [2, 3],
            //         [3, 4]]])
            // 

#if TODO
            var given = a = cp.array((1,2,3));
             given = b = cp.array((2,3,4));
             given = cp.dstack((a,b));
            var expected =
                "array([[[1, 2],\n" +
                "        [2, 3],\n" +
                "        [3, 4]]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> a = cp.array([[1],[2],[3]])
            // >>> b = cp.array([[2],[3],[4]])
            // >>> cp.dstack((a,b))
            // array([[[1, 2]],
            //        [[2, 3]],
            //        [[3, 4]]])
            // 

#if TODO
             given = a = cp.array({{1},{2},{3}});
             given = b = cp.array({{2},{3},{4}});
             given = cp.dstack((a,b));
             expected =
                "array([[[1, 2]],\n" +
                "       [[2, 3]],\n" +
                "       [[3, 4]]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void hstackTest()
        {
            // >>> a = cp.array((1,2,3))
            // >>> b = cp.array((2,3,4))
            // >>> cp.hstack((a,b))
            // array([1, 2, 3, 2, 3, 4])
            // >>> a = cp.array([[1],[2],[3]])
            // >>> b = cp.array([[2],[3],[4]])
            // >>> cp.hstack((a,b))
            // array([[1, 2],
            //        [2, 3],
            //        [3, 4]])
            // 

#if TODO
            var given = a = cp.array((1,2,3));
             given = b = cp.array((2,3,4));
             given = cp.hstack((a,b));
            var expected =
                "array([1, 2, 3, 2, 3, 4])";
            Assert.AreEqual(expected, given.repr);
             given = a = cp.array({{1},{2},{3}});
             given = b = cp.array({{2},{3},{4}});
             given = cp.hstack((a,b));
             expected =
                "array([[1, 2],\n" +
                "       [2, 3],\n" +
                "       [3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void vstackTest()
        {
            // >>> a = cp.array([1, 2, 3])
            // >>> b = cp.array([2, 3, 4])
            // >>> cp.vstack((a,b))
            // array([[1, 2, 3],
            //        [2, 3, 4]])
            // 

#if TODO
            var given = a = cp.array({1, 2, 3});
             given = b = cp.array({2, 3, 4});
             given = cp.vstack((a,b));
            var expected =
                "array([[1, 2, 3],\n" +
                "       [2, 3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> a = cp.array([[1], [2], [3]])
            // >>> b = cp.array([[2], [3], [4]])
            // >>> cp.vstack((a,b))
            // array([[1],
            //        [2],
            //        [3],
            //        [2],
            //        [3],
            //        [4]])
            // 

#if TODO
             given = a = cp.array({{1}, {2}, {3}});
             given = b = cp.array({{2}, {3}, {4}});
             given = cp.vstack((a,b));
             expected =
                "array([[1],\n" +
                "       [2],\n" +
                "       [3],\n" +
                "       [2],\n" +
                "       [3],\n" +
                "       [4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void blockTest()
        {
            // The most common use of this function is to build a block matrix

            // >>> A = cp.eye(2) * 2
            // >>> B = cp.eye(3) * 3
            // >>> cp.block([
            // ...     [A,               cp.zeros((2, 3))],
            // ...     [cp.ones((3, 2)), B               ]
            // ... ])
            // array([[ 2.,  0.,  0.,  0.,  0.],
            //        [ 0.,  2.,  0.,  0.,  0.],
            //        [ 1.,  1.,  3.,  0.,  0.],
            //        [ 1.,  1.,  0.,  3.,  0.],
            //        [ 1.,  1.,  0.,  0.,  3.]])
            // 

#if TODO
            var given = A = cp.eye(2) * 2;
             given = B = cp.eye(3) * 3;
             given = cp.block({;
            var expected =
                "...     [A,               cp.zeros((2, 3))],\n" +
                "...     [cp.ones((3, 2)), B               ]\n" +
                "... ])\n" +
                "array([[ 2.,  0.,  0.,  0.,  0.],\n" +
                "       [ 0.,  2.,  0.,  0.,  0.],\n" +
                "       [ 1.,  1.,  3.,  0.,  0.],\n" +
                "       [ 1.,  1.,  0.,  3.,  0.],\n" +
                "       [ 1.,  1.,  0.,  0.,  3.]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // With a list of depth 1, block can be used as hstack

            // >>> cp.block([1, 2, 3])              # hstack([1, 2, 3])
            // array([1, 2, 3])
            // 

#if TODO
             given = cp.block({1, 2, 3})              # hstack({1, 2, 3});
             expected =
                "array([1, 2, 3])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> a = cp.array([1, 2, 3])
            // >>> b = cp.array([2, 3, 4])
            // >>> cp.block([a, b, 10])             # hstack([a, b, 10])
            // array([1, 2, 3, 2, 3, 4, 10])
            // 

#if TODO
             given = a = cp.array({1, 2, 3});
             given = b = cp.array({2, 3, 4});
             given = cp.block({a, b, 10})             # hstack({a, b, 10});
             expected =
                "array([1, 2, 3, 2, 3, 4, 10])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> A = cp.ones((2, 2), int)
            // >>> B = 2 * A
            // >>> cp.block([A, B])                 # hstack([A, B])
            // array([[1, 1, 2, 2],
            //        [1, 1, 2, 2]])
            // 

#if TODO
             given = A = cp.ones((2, 2), int);
             given = B = 2 * A;
             given = cp.block({A, B})                 # hstack({A, B});
             expected =
                "array([[1, 1, 2, 2],\n" +
                "       [1, 1, 2, 2]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // With a list of depth 2, block can be used in place of vstack:

            // >>> a = cp.array([1, 2, 3])
            // >>> b = cp.array([2, 3, 4])
            // >>> cp.block([[a], [b]])             # vstack([a, b])
            // array([[1, 2, 3],
            //        [2, 3, 4]])
            // 

#if TODO
             given = a = cp.array({1, 2, 3});
             given = b = cp.array({2, 3, 4});
             given = cp.block({{a}, {b}})             # vstack({a, b});
             expected =
                "array([[1, 2, 3],\n" +
                "       [2, 3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> A = cp.ones((2, 2), int)
            // >>> B = 2 * A
            // >>> cp.block([[A], [B]])             # vstack([A, B])
            // array([[1, 1],
            //        [1, 1],
            //        [2, 2],
            //        [2, 2]])
            // 

#if TODO
             given = A = cp.ones((2, 2), int);
             given = B = 2 * A;
             given = cp.block({{A}, {B}})             # vstack({A, B});
             expected =
                "array([[1, 1],\n" +
                "       [1, 1],\n" +
                "       [2, 2],\n" +
                "       [2, 2]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // It can also be used in places of atleast_1d and atleast_2d

            // >>> a = cp.array(0)
            // >>> b = cp.array([1])
            // >>> cp.block([a])                    # atleast_1d(a)
            // array([0])
            // >>> cp.block([b])                    # atleast_1d(b)
            // array([1])
            // 

#if TODO
             given = a = cp.array(0);
             given = b = cp.array({1});
             given = cp.block({a})                    # atleast_1d(a);
             expected =
                "array([0])";
            Assert.AreEqual(expected, given.repr);
             given = cp.block({b})                    # atleast_1d(b);
             expected =
                "array([1])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.block([[a]])                  # atleast_2d(a)
            // array([[0]])
            // >>> cp.block([[b]])                  # atleast_2d(b)
            // array([[1]])
            // 

#if TODO
             given = cp.block({{a}})                  # atleast_2d(a);
             expected =
                "array([[0]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.block({{b}})                  # atleast_2d(b);
             expected =
                "array([[1]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void splitTest()
        {
            // >>> x = cp.arange(9.0)
            // >>> cp.split(x, 3)
            // [array([ 0.,  1.,  2.]), array([ 3.,  4.,  5.]), array([ 6.,  7.,  8.])]
            // 

#if TODO
            var given = x = cp.arange(9.0);
             given = cp.split(x, 3);
            var expected =
                "[array([ 0.,  1.,  2.]), array([ 3.,  4.,  5.]), array([ 6.,  7.,  8.])]";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x = cp.arange(8.0)
            // >>> cp.split(x, [3, 5, 6, 10])
            // [array([ 0.,  1.,  2.]),
            //  array([ 3.,  4.]),
            //  array([ 5.]),
            //  array([ 6.,  7.]),
            //  array([], dtype=float64)]
            // 

#if TODO
             given = x = cp.arange(8.0);
             given = cp.split(x, {3, 5, 6, 10});
             expected =
                "[array([ 0.,  1.,  2.]),\n" +
                " array([ 3.,  4.]),\n" +
                " array([ 5.]),\n" +
                " array([ 6.,  7.]),\n" +
                " array([], dtype=float64)]";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void tileTest()
        {
            // >>> a = cp.array([0, 1, 2])
            // >>> cp.tile(a, 2)
            // array([0, 1, 2, 0, 1, 2])
            // >>> cp.tile(a, (2, 2))
            // array([[0, 1, 2, 0, 1, 2],
            //        [0, 1, 2, 0, 1, 2]])
            // >>> cp.tile(a, (2, 1, 2))
            // array([[[0, 1, 2, 0, 1, 2]],
            //        [[0, 1, 2, 0, 1, 2]]])
            // 

#if TODO
            var given = a = cp.array({0, 1, 2});
             given = cp.tile(a, 2);
            var expected =
                "array([0, 1, 2, 0, 1, 2])";
            Assert.AreEqual(expected, given.repr);
             given = cp.tile(a, (2, 2));
             expected =
                "array([[0, 1, 2, 0, 1, 2],\n" +
                "       [0, 1, 2, 0, 1, 2]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.tile(a, (2, 1, 2));
             expected =
                "array([[[0, 1, 2, 0, 1, 2]],\n" +
                "       [[0, 1, 2, 0, 1, 2]]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> b = cp.array([[1, 2], [3, 4]])
            // >>> cp.tile(b, 2)
            // array([[1, 2, 1, 2],
            //        [3, 4, 3, 4]])
            // >>> cp.tile(b, (2, 1))
            // array([[1, 2],
            //        [3, 4],
            //        [1, 2],
            //        [3, 4]])
            // 

#if TODO
             given = b = cp.array({{1, 2}, {3, 4}});
             given = cp.tile(b, 2);
             expected =
                "array([[1, 2, 1, 2],\n" +
                "       [3, 4, 3, 4]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.tile(b, (2, 1));
             expected =
                "array([[1, 2],\n" +
                "       [3, 4],\n" +
                "       [1, 2],\n" +
                "       [3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> c = cp.array([1,2,3,4])
            // >>> cp.tile(c,(4,1))
            // array([[1, 2, 3, 4],
            //        [1, 2, 3, 4],
            //        [1, 2, 3, 4],
            //        [1, 2, 3, 4]])
            // 

#if TODO
             given = c = cp.array({1,2,3,4});
             given = cp.tile(c,(4,1));
             expected =
                "array([[1, 2, 3, 4],\n" +
                "       [1, 2, 3, 4],\n" +
                "       [1, 2, 3, 4],\n" +
                "       [1, 2, 3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void repeatTest()
        {
            // >>> cp.repeat(3, 4)
            // array([3, 3, 3, 3])
            // >>> x = cp.array([[1,2],[3,4]])
            // >>> cp.repeat(x, 2)
            // array([1, 1, 2, 2, 3, 3, 4, 4])
            // >>> cp.repeat(x, 3, axis=1)
            // array([[1, 1, 1, 2, 2, 2],
            //        [3, 3, 3, 4, 4, 4]])
            // >>> cp.repeat(x, [1, 2], axis=0)
            // array([[1, 2],
            //        [3, 4],
            //        [3, 4]])
            // 

#if TODO
            var given = cp.repeat(3, 4);
            var expected =
                "array([3, 3, 3, 3])";
            Assert.AreEqual(expected, given.repr);
             given = x = cp.array({{1,2},{3,4}});
             given = cp.repeat(x, 2);
             expected =
                "array([1, 1, 2, 2, 3, 3, 4, 4])";
            Assert.AreEqual(expected, given.repr);
             given = cp.repeat(x, 3, axis = 1);
             expected =
                "array([[1, 1, 1, 2, 2, 2],\n" +
                "       [3, 3, 3, 4, 4, 4]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.repeat(x, {1, 2}, axis = 0);
             expected =
                "array([[1, 2],\n" +
                "       [3, 4],\n" +
                "       [3, 4]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }

#if NOT_IMPLEMENTED
        [Test]
        public void deleteTest()
        {
            // >>> arr = cp.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
            // >>> arr
            // array([[ 1,  2,  3,  4],
            //        [ 5,  6,  7,  8],
            //        [ 9, 10, 11, 12]])
            // >>> cp.delete(arr, 1, 0)
            // array([[ 1,  2,  3,  4],
            //        [ 9, 10, 11, 12]])
            // 

            NDarray given = cp.array(new[,] { { 1, 2, 3, 4 }, { 5, 6, 7, 8 }, { 9, 10, 11, 12 } });
            var arr = given;
            var expected =
                "array([[ 1,  2,  3,  4],\n" +
                "       [ 5,  6,  7,  8],\n" +
                "       [ 9, 10, 11, 12]])";
            Assert.AreEqual(expected, given.repr);
            given = cp.delete(arr, 1, 0);
            expected =
                "array([[ 1,  2,  3,  4],\n" +
                "       [ 9, 10, 11, 12]])";
            Assert.AreEqual(expected, given.repr);

            // >>> cp.delete(arr, cp.s_[::2], 1)
            // array([[ 2,  4],
            //        [ 6,  8],
            //        [10, 12]])
            // >>> cp.delete(arr, [1,3,5], None)
            // array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])
            // 


            given = arr.delete(new Slice("::2"), 1);
            expected =
                "array([[ 2,  4],\n" +
                "       [ 6,  8],\n" +
                "       [10, 12]])";
            Assert.AreEqual(expected, given.repr);
            given = cp.delete(arr, new[] { 1, 3, 5 });
            expected =
                "array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])";
            Assert.AreEqual(expected, given.repr);
        }
#endif


        [Test]
        public void insertTest()
        {
            // >>> a = cp.array([[1, 1], [2, 2], [3, 3]])
            // >>> a
            // array([[1, 1],
            //        [2, 2],
            //        [3, 3]])
            // >>> cp.insert(a, 1, 5)
            // array([1, 5, 1, 2, 2, 3, 3])
            // >>> cp.insert(a, 1, 5, axis=1)
            // array([[1, 5, 1],
            //        [2, 5, 2],
            //        [3, 5, 3]])
            // 

            NDarray a = cp.array(new[,] { { 1, 1 }, { 2, 2 }, { 3, 3 } });
            var given = a;
            var expected =
                "array([[1, 1],\n" +
                "       [2, 2],\n" +
                "       [3, 3]])";
            Assert.AreEqual(expected, given.repr);
            given = cp.insert(a, 1, 5);
            expected =
                "array([1, 5, 1, 2, 2, 3, 3])";
            Assert.AreEqual(expected, given.repr);
            given = cp.insert(a, 1, 5, 1);
            expected =
                "array([[1, 5, 1],\n" +
                "       [2, 5, 2],\n" +
                "       [3, 5, 3]])";
            Assert.AreEqual(expected, given.repr);

            // Difference between sequence and scalars:

            // >>> cp.insert(a, [1], [[1],[2],[3]], axis=1)
            // array([[1, 1, 1],
            //        [2, 2, 2],
            //        [3, 3, 3]])
            given = cp.insert(a, cp.array(1), cp.array(new[,] { { 1 }, { 2 }, { 3 } }), 1);
            expected =
                "array([[1, 1, 1],\n" +
                "       [2, 2, 2],\n" +
                "       [3, 3, 3]])";

            // >>> cp.array_equal(cp.insert(a, 1, [1, 2, 3], axis=1),
            // ...                cp.insert(a, [1], [[1],[2],[3]], axis=1))
            // True
            // 
            Assert.AreEqual(expected, given.repr);
            var equal = cp.insert(a, 1, cp.array(1, 2, 3), 1)
                .array_equal(cp.insert(a, cp.array(1), cp.array(new[,] { { 1 }, { 2 }, { 3 } }), 1));
            Assert.AreEqual(true, equal);

            // >>> b = a.flatten()
            // >>> b
            // array([1, 1, 2, 2, 3, 3])
            // >>> cp.insert(b, [2, 2], [5, 6])
            // array([1, 1, 5, 6, 2, 2, 3, 3])
            // 

            var b = a.flatten();
            given = b;
            expected =
                "array([1, 1, 2, 2, 3, 3])";
            Assert.AreEqual(expected, given.repr);
            given = cp.insert(b, cp.array(2, 2), cp.array(5, 6));
            expected =
                "array([1, 1, 5, 6, 2, 2, 3, 3])";
            Assert.AreEqual(expected, given.repr);

            // >>> cp.insert(b, slice(2, 4), [5, 6])
            // array([1, 1, 5, 2, 6, 2, 3, 3])
            // 

            given = cp.insert(b, new Slice(2, 4), cp.array(5, 6));
            expected =
                "array([1, 1, 5, 2, 6, 2, 3, 3])";
            Assert.AreEqual(expected, given.repr);
            // >>> cp.insert(b, [2, 2], [7.13, False]) # type casting
            // array([1, 1, 7, 0, 2, 2, 3, 3])
            // 

#if NOT_SUPPORTED
            given = cp.insert(b, cp.array(new[] { 2, 2 }), cp.array(new object[] { 7.13, false })); // type casting
            expected =
                "array([1, 1, 7, 0, 2, 2, 3, 3])";
            Assert.AreEqual(expected, given.repr);
#endif

            // >>> x = cp.arange(8).reshape(2, 4)
            // >>> idx = (1, 3)
            // >>> cp.insert(x, idx, 999, axis=1)
            // array([[  0, 999,   1,   2, 999,   3],
            //        [  4, 999,   5,   6, 999,   7]])
            // 


            var x = cp.arange(8).reshape(2, 4);
            NDarray idx = cp.array(1, 3);
            given = cp.insert(x, idx, cp.array(999), 1);
            expected =
                "array([[  0, 999,   1,   2, 999,   3],\n" +
                "       [  4, 999,   5,   6, 999,   7]])";
            Assert.AreEqual(expected, given.repr);
        }


        [Test]
        public void appendTest()
        {
            // >>> cp.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
            // array([1, 2, 3, 4, 5, 6, 7, 8, 9])
            // 

            var given = cp.append(new[] { 1, 2, 3 }, new[,] { { 4, 5, 6 }, { 7, 8, 9 } });
            var expected =
                "array([1, 2, 3, 4, 5, 6, 7, 8, 9])";
            Assert.AreEqual(expected, given.repr);
            // When axis is specified, values must have the correct shape.

            // >>> cp.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)
            // array([[1, 2, 3],
            //        [4, 5, 6],
            //        [7, 8, 9]])

            given = cp.append(new[,] { { 1, 2, 3 }, { 4, 5, 6 } }, new[,] { { 7, 8, 9 } }, 0);
            expected =
                "array([[1, 2, 3],\n" +
                "       [4, 5, 6],\n" +
                "       [7, 8, 9]])";
            Assert.AreEqual(expected, given.repr);
        }


        [Test]
        public void resizeTest()
        {
            // >>> a=cp.array([[0,1],[2,3]])
            // >>> cp.resize(a,(2,3))
            // array([[0, 1, 2],
            //        [3, 0, 1]])
            // >>> cp.resize(a,(1,4))
            // array([[0, 1, 2, 3]])
            // >>> cp.resize(a,(2,4))
            // array([[0, 1, 2, 3],
            //        [0, 1, 2, 3]])
            // 

#if TODO
            var given = a = cp.array({{0,1},{2,3}});
             given = cp.resize(a,(2,3));
            var expected =
                "array([[0, 1, 2],\n" +
                "       [3, 0, 1]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.resize(a,(1,4));
             expected =
                "array([[0, 1, 2, 3]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.resize(a,(2,4));
             expected =
                "array([[0, 1, 2, 3],\n" +
                "       [0, 1, 2, 3]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void trim_zerosTest()
        {
            // >>> a = cp.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
            // >>> cp.trim_zeros(a)
            // array([1, 2, 3, 0, 2, 1])
            // 

#if TODO
            var given = a = cp.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0));
             given = cp.trim_zeros(a);
            var expected =
                "array([1, 2, 3, 0, 2, 1])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.trim_zeros(a, 'b')
            // array([0, 0, 0, 1, 2, 3, 0, 2, 1])
            // 

#if TODO
             given = cp.trim_zeros(a, 'b');
             expected =
                "array([0, 0, 0, 1, 2, 3, 0, 2, 1])";
            Assert.AreEqual(expected, given.repr);
#endif
            // The input data type is preserved, list/tuple in means list/tuple out.

            // >>> cp.trim_zeros([0, 1, 2, 0])
            // [1, 2]
            // 

#if TODO
             given = cp.trim_zeros({0, 1, 2, 0});
             expected =
                "[1, 2]";
            Assert.AreEqual(expected, given.repr);
#endif
        }

        [Test]
        public void uniqueTest()
        {
            // >>> cp.unique([1, 1, 2, 2, 3, 3])
            // array([1, 2, 3])
            // >>> a = cp.array([[1, 1], [2, 3]])
            // >>> cp.unique(a)
            // array([1, 2, 3])
            // 

            var given = cp.unique(new[] { 1, 1, 2, 2, 3, 3 });
            var expected =
                "array([1, 2, 3])";
            Assert.AreEqual(expected, given.repr);
            var a = cp.array(new[,] { { 1, 1 }, { 2, 3 } });
            given = cp.unique(a);
            expected =
                "array([1, 2, 3])";
            Assert.AreEqual(expected, given.repr);
            // Return the unique rows of a 2D array

            // >>> a = cp.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
            // >>> cp.unique(a, axis=0)
            // array([[1, 0, 0], [2, 3, 4]])
            // 


            a = cp.array(new[,] { { 1, 0, 0 }, { 1, 0, 0 }, { 2, 3, 4 } });
            given = cp.unique(a, 0);
            expected =
                "array([[1, 0, 0],\n       [2, 3, 4]])";
            Assert.AreEqual(expected, given.repr);

            // Return the indices of the original array that give the unique values:

            // >>> a = cp.array(['a', 'b', 'b', 'c', 'a'])
            // >>> u, indices = cp.unique(a, return_index=True)
            // >>> u
            // array(['a', 'b', 'c'],
            //        dtype='|S1')
            // >>> indices
            // array([0, 1, 3])
            // >>> a[indices]
            // array(['a', 'b', 'c'],
            //        dtype='|S1')
            // 

            var a1 = cp.array(1, 2, 2, 3, 1);
            var rv = a1.unique(true, false, false);
            var (u, indices) = (rv[0], rv[1]);
            given = u;
            expected =
                "array([1, 2, 3])";
            Assert.AreEqual(expected, given.repr);
            given = indices;
            expected =
                "array([0, 1, 3], dtype=int64)";
            Assert.AreEqual(expected, given.repr);
            given = a1[indices];
            expected =
                "array([1, 2, 3])";
            Assert.AreEqual(expected, given.repr);

            // Reconstruct the input array from the unique values:

            // >>> a = cp.array([1, 2, 6, 4, 2, 3, 2])
            // >>> u, indices = cp.unique(a, return_inverse=True)
            // >>> u
            // array([1, 2, 3, 4, 6])
            // >>> indices
            // array([0, 1, 4, 3, 1, 2, 1])
            // >>> u[indices]
            // array([1, 2, 6, 4, 2, 3, 2])
            // 

            a = cp.array(1, 2, 6, 4, 2, 3, 2);
            rv = a.unique(return_inverse: true, return_counts: false, return_index: false);
            (u, indices) = (rv[0], rv[1]);
            given = u;
            expected =
                "array([1, 2, 3, 4, 6])";
            Assert.AreEqual(expected, given.repr);
            given = indices;
            expected =
                "array([0, 1, 4, 3, 1, 2, 1], dtype=int64)";
            Assert.AreEqual(expected, given.repr);
            given = u[indices];
            expected =
                "array([1, 2, 6, 4, 2, 3, 2])";
            Assert.AreEqual(expected, given.repr);
        }

        [Test]
        public void flipTest()
        {
            // >>> A = cp.arange(8).reshape((2,2,2))
            // >>> A
            // array([[[0, 1],
            //         [2, 3]],
            //        [[4, 5],
            //         [6, 7]]])
            // >>> flip(A, 0)
            // array([[[4, 5],
            //         [6, 7]],
            //        [[0, 1],
            //         [2, 3]]])
            // >>> flip(A, 1)
            // array([[[2, 3],
            //         [0, 1]],
            //        [[6, 7],
            //         [4, 5]]])
            // >>> cp.flip(A)
            // array([[[7, 6],
            //         [5, 4]],
            //        [[3, 2],
            //         [1, 0]]])
            // >>> cp.flip(A, (0, 2))
            // array([[[5, 4],
            //         [7, 6]],
            //        [[1, 0],
            //         [3, 2]]])
            // >>> A = cp.random.randn(3,4,5)
            // >>> cp.all(flip(A,2) == A[:,:,::-1,...])
            // True
            // 

#if TODO
            var given = A = cp.arange(8).reshape((2,2,2));
             given = A;
            var expected =
                "array([[[0, 1],\n" +
                "        [2, 3]],\n" +
                "       [[4, 5],\n" +
                "        [6, 7]]])";
            Assert.AreEqual(expected, given.repr);
             given = flip(A, 0);
             expected =
                "array([[[4, 5],\n" +
                "        [6, 7]],\n" +
                "       [[0, 1],\n" +
                "        [2, 3]]])";
            Assert.AreEqual(expected, given.repr);
             given = flip(A, 1);
             expected =
                "array([[[2, 3],\n" +
                "        [0, 1]],\n" +
                "       [[6, 7],\n" +
                "        [4, 5]]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.flip(A);
             expected =
                "array([[[7, 6],\n" +
                "        [5, 4]],\n" +
                "       [[3, 2],\n" +
                "        [1, 0]]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.flip(A, (0, 2));
             expected =
                "array([[[5, 4],\n" +
                "        [7, 6]],\n" +
                "       [[1, 0],\n" +
                "        [3, 2]]])";
            Assert.AreEqual(expected, given.repr);
             given = A = cp.random.randn(3,4,5);
             given = cp.all(flip(A,2) == A{:,:,::-1,...});
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void fliplrTest()
        {
            // >>> A = cp.diag([1.,2.,3.])
            // >>> A
            // array([[ 1.,  0.,  0.],
            //        [ 0.,  2.,  0.],
            //        [ 0.,  0.,  3.]])
            // >>> cp.fliplr(A)
            // array([[ 0.,  0.,  1.],
            //        [ 0.,  2.,  0.],
            //        [ 3.,  0.,  0.]])
            // 

#if TODO
            var given = A = cp.diag({1.,2.,3.});
             given = A;
            var expected =
                "array([[ 1.,  0.,  0.],\n" +
                "       [ 0.,  2.,  0.],\n" +
                "       [ 0.,  0.,  3.]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.fliplr(A);
             expected =
                "array([[ 0.,  0.,  1.],\n" +
                "       [ 0.,  2.,  0.],\n" +
                "       [ 3.,  0.,  0.]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> A = cp.random.randn(2,3,5)
            // >>> cp.all(cp.fliplr(A) == A[:,::-1,...])
            // True
            // 

#if TODO
             given = A = cp.random.randn(2,3,5);
             given = cp.all(cp.fliplr(A) == A{:,::-1,...});
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void flipudTest()
        {
            // >>> A = cp.diag([1.0, 2, 3])
            // >>> A
            // array([[ 1.,  0.,  0.],
            //        [ 0.,  2.,  0.],
            //        [ 0.,  0.,  3.]])
            // >>> cp.flipud(A)
            // array([[ 0.,  0.,  3.],
            //        [ 0.,  2.,  0.],
            //        [ 1.,  0.,  0.]])
            // 

#if TODO
            var given = A = cp.diag({1.0, 2, 3});
             given = A;
            var expected =
                "array([[ 1.,  0.,  0.],\n" +
                "       [ 0.,  2.,  0.],\n" +
                "       [ 0.,  0.,  3.]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.flipud(A);
             expected =
                "array([[ 0.,  0.,  3.],\n" +
                "       [ 0.,  2.,  0.],\n" +
                "       [ 1.,  0.,  0.]])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> A = cp.random.randn(2,3,5)
            // >>> cp.all(cp.flipud(A) == A[::-1,...])
            // True
            // 

#if TODO
             given = A = cp.random.randn(2,3,5);
             given = cp.all(cp.flipud(A) == A{::-1,...});
             expected =
                "True";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> cp.flipud([1,2])
            // array([2, 1])
            // 

#if TODO
             given = cp.flipud({1,2});
             expected =
                "array([2, 1])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void rollTest()
        {
            // >>> x = cp.arange(10)
            // >>> cp.roll(x, 2)
            // array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])
            // 

#if TODO
            var given = x = cp.arange(10);
             given = cp.roll(x, 2);
            var expected =
                "array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])";
            Assert.AreEqual(expected, given.repr);
#endif
            // >>> x2 = cp.reshape(x, (2,5))
            // >>> x2
            // array([[0, 1, 2, 3, 4],
            //        [5, 6, 7, 8, 9]])
            // >>> cp.roll(x2, 1)
            // array([[9, 0, 1, 2, 3],
            //        [4, 5, 6, 7, 8]])
            // >>> cp.roll(x2, 1, axis=0)
            // array([[5, 6, 7, 8, 9],
            //        [0, 1, 2, 3, 4]])
            // >>> cp.roll(x2, 1, axis=1)
            // array([[4, 0, 1, 2, 3],
            //        [9, 5, 6, 7, 8]])
            // 

#if TODO
             given = x2 = cp.reshape(x, (2,5));
             given = x2;
             expected =
                "array([[0, 1, 2, 3, 4],\n" +
                "       [5, 6, 7, 8, 9]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.roll(x2, 1);
             expected =
                "array([[9, 0, 1, 2, 3],\n" +
                "       [4, 5, 6, 7, 8]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.roll(x2, 1, axis = 0);
             expected =
                "array([[5, 6, 7, 8, 9],\n" +
                "       [0, 1, 2, 3, 4]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.roll(x2, 1, axis = 1);
             expected =
                "array([[4, 0, 1, 2, 3],\n" +
                "       [9, 5, 6, 7, 8]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }


        [Test]
        public void rot90Test()
        {
            // >>> m = cp.array([[1,2],[3,4]], int)
            // >>> m
            // array([[1, 2],
            //        [3, 4]])
            // >>> cp.rot90(m)
            // array([[2, 4],
            //        [1, 3]])
            // >>> cp.rot90(m, 2)
            // array([[4, 3],
            //        [2, 1]])
            // >>> m = cp.arange(8).reshape((2,2,2))
            // >>> cp.rot90(m, 1, (1,2))
            // array([[[1, 3],
            //         [0, 2]],
            //        [[5, 7],
            //         [4, 6]]])
            // 

#if TODO
            var given = m = cp.array({{1,2},{3,4}}, int);
             given = m;
            var expected =
                "array([[1, 2],\n" +
                "       [3, 4]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.rot90(m);
             expected =
                "array([[2, 4],\n" +
                "       [1, 3]])";
            Assert.AreEqual(expected, given.repr);
             given = cp.rot90(m, 2);
             expected =
                "array([[4, 3],\n" +
                "       [2, 1]])";
            Assert.AreEqual(expected, given.repr);
             given = m = cp.arange(8).reshape((2,2,2));
             given = cp.rot90(m, 1, (1,2));
             expected =
                "array([[[1, 3],\n" +
                "        [0, 2]],\n" +
                "       [[5, 7],\n" +
                "        [4, 6]]])";
            Assert.AreEqual(expected, given.repr);
#endif
        }
    }
}